import Link from "next/link";
import { Activity, AlertTriangle, CheckCircle2, Clock3, UsersRound } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireProductRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { OdkPanelNav } from "@/components/odk/odk-panel-nav";

export const dynamic = "force-dynamic";
const time = new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Istanbul" });

export default async function OdkOperationsPage() {
  const session = await requireProductRole("ODK", "ADMIN"); const now = new Date(); const staleBefore = new Date(now.getTime() - 2 * 60_000);
  const exams = await prisma.odkExam.findMany({
    where: { status: { in: ["SCHEDULED", "LIVE"] }, endsAt: { gte: new Date(now.getTime() - 24 * 60 * 60_000) } }, orderBy: { startsAt: "asc" }, take: 30,
    select: { id: true, title: true, family: true, status: true, startsAt: true, endsAt: true, meetRequired: true, attempts: { where: { status: { not: "VOID" } }, orderBy: { startedAt: "asc" }, select: { id: true, status: true, meetAcknowledgedAt: true, startedAt: true, deadlineAt: true, lastActivityAt: true, student: { select: { fullName: true, email: true } }, _count: { select: { answers: true } } } } },
  });
  const attempts = exams.flatMap((exam) => exam.attempts.map((attempt) => ({ ...attempt, examId: exam.id, examTitle: exam.title })));
  const active = attempts.filter((attempt) => attempt.status === "IN_PROGRESS" && attempt.deadlineAt > now);
  const stale = active.filter((attempt) => attempt.lastActivityAt < staleBefore);
  const submitted = attempts.filter((attempt) => attempt.status === "SUBMITTED" || attempt.status === "AUTO_SUBMITTED");
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} product="ODK" nav={<OdkPanelNav role={session.role} />}>
    <header><p className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.09em] text-[var(--brand-olive)]"><Activity size={15} /> Canlı operasyon</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-[var(--site-ink)]">Sınav akışını tek ekrandan izleyin.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--site-body)]">Tarayıcı kalp atışı bağlantı görünürlüğü sağlar; Google Meet katılımının teknik doğrulaması değildir. Şüpheli durumda öğrenciyle doğrudan iletişim kurun.</p></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Aktif sınav", exams.filter((exam) => exam.startsAt && exam.startsAt <= now && exam.endsAt && exam.endsAt > now).length, Activity], ["Aktif öğrenci", active.length, UsersRound], ["Teslim", submitted.length, CheckCircle2], ["Kalp atışı geciken", stale.length, AlertTriangle]].map(([label, value, Icon]) => { const MetricIcon = Icon as typeof Activity; return <article key={String(label)} className="panel-metric-card"><MetricIcon size={18} className={label === "Kalp atışı geciken" && Number(value) ? "text-amber-600" : "text-[var(--brand-olive)]"} /><p className="mt-4 text-2xl font-black text-[var(--site-ink)]">{String(value)}</p><p className="mt-1 text-xs text-[var(--site-muted)]">{String(label)}</p></article>; })}</section>
    <section className="mt-6 space-y-4">{exams.map((exam) => { const isLive = exam.startsAt && exam.startsAt <= now && exam.endsAt && exam.endsAt > now; return <article key={exam.id} className="panel-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${isLive ? "animate-pulse bg-red-500" : "bg-slate-300"}`} /><p className="text-xs font-black text-[var(--brand-olive)]">{exam.family} · {isLive ? "CANLI" : "PLANLANDI"}</p></div><h2 className="mt-2 text-lg font-extrabold text-[var(--site-ink)]">{exam.title}</h2><p className="mt-1 text-xs text-[var(--site-muted)]">{exam.startsAt ? time.format(exam.startsAt) : "—"} – {exam.endsAt ? time.format(exam.endsAt) : "—"}</p></div><Link href={`/panel/odk/yonetim/sinavlar/${exam.id}`} className="panel-quick-action">Deneme yönetimi</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead><tr className="border-b border-[var(--site-border)] text-left text-[10px] uppercase text-[var(--site-muted)]"><th className="pb-2">Öğrenci</th><th>Durum</th><th>Cevap</th><th>Son kalp atışı</th><th>Meet onayı</th></tr></thead><tbody>{exam.attempts.map((attempt) => { const isStale = attempt.status === "IN_PROGRESS" && attempt.lastActivityAt < staleBefore; return <tr key={attempt.id} className="border-b border-[var(--site-border)] last:border-0"><td className="py-3 font-bold text-[var(--site-ink)]">{attempt.student.fullName || attempt.student.email}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${attempt.status === "IN_PROGRESS" ? "bg-blue-50 text-blue-700" : "bg-emerald-50 text-emerald-700"}`}>{attempt.status === "IN_PROGRESS" ? "Çözüyor" : attempt.status === "AUTO_SUBMITTED" ? "Otomatik teslim" : "Teslim"}</span></td><td>{attempt._count.answers}</td><td className={isStale ? "font-bold text-amber-700" : "text-[var(--site-body)]"}>{isStale ? "Gecikiyor · " : ""}{time.format(attempt.lastActivityAt)}</td><td>{!exam.meetRequired ? "Gerekmiyor" : attempt.meetAcknowledgedAt ? "Onaylandı" : "Eksik"}</td></tr>; })}</tbody></table>{!exam.attempts.length ? <p className="py-5 text-sm text-[var(--site-muted)]">Henüz sınava giren öğrenci yok.</p> : null}</div></article>; })}{!exams.length ? <div className="rounded-3xl border border-dashed border-[var(--site-border)] bg-white p-8 text-center"><Clock3 size={22} className="mx-auto text-[var(--site-muted)]" /><p className="mt-3 text-sm text-[var(--site-muted)]">İzlenecek planlı veya canlı deneme bulunmuyor.</p></div> : null}</section>
  </PanelShell>;
}
