-- Remove the legacy role-based panel while preserving public leads, catalog,
-- guest orders, payments, coupons, email outbox and payment audit records.

DROP TABLE IF EXISTS "VerificationCode" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Student" CASCADE;
DROP TABLE IF EXISTS "Teacher" CASCADE;
DROP TABLE IF EXISTS "StudentPackage" CASCADE;
DROP TABLE IF EXISTS "Camp" CASCADE;
DROP TABLE IF EXISTS "Lesson" CASCADE;
DROP TABLE IF EXISTS "LessonJoinEvent" CASCADE;
DROP TABLE IF EXISTS "StudentPackageEnrollment" CASCADE;
DROP TABLE IF EXISTS "Course" CASCADE;
DROP TABLE IF EXISTS "CourseModule" CASCADE;
DROP TABLE IF EXISTS "CourseContent" CASCADE;
DROP TABLE IF EXISTS "PackageCourse" CASCADE;
DROP TABLE IF EXISTS "StudentCourseProgress" CASCADE;
DROP TABLE IF EXISTS "StudentContentProgress" CASCADE;
DROP TABLE IF EXISTS "StudentGoal" CASCADE;
DROP TABLE IF EXISTS "StudentExamResult" CASCADE;
DROP TABLE IF EXISTS "StudentExamSubjectStat" CASCADE;
DROP TABLE IF EXISTS "StudentExamTopicStat" CASCADE;
DROP TABLE IF EXISTS "StudentMetricSnapshot" CASCADE;
DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "odk_exam_series" CASCADE;
DROP TABLE IF EXISTS "odk_exams" CASCADE;
DROP TABLE IF EXISTS "odk_exam_sections" CASCADE;
DROP TABLE IF EXISTS "odk_exam_official_answers" CASCADE;
DROP TABLE IF EXISTS "odk_exam_files" CASCADE;
DROP TABLE IF EXISTS "odk_access_tags" CASCADE;
DROP TABLE IF EXISTS "odk_user_access_tags" CASCADE;
DROP TABLE IF EXISTS "odk_exam_access_tags" CASCADE;
DROP TABLE IF EXISTS "odk_package_exams" CASCADE;
DROP TABLE IF EXISTS "odk_package_access_tags" CASCADE;
DROP TABLE IF EXISTS "odk_entitlements" CASCADE;
DROP TABLE IF EXISTS "odk_exam_attempts" CASCADE;
DROP TABLE IF EXISTS "odk_exam_attempt_events" CASCADE;
DROP TABLE IF EXISTS "odk_attempt_optical_answers" CASCADE;
DROP TABLE IF EXISTS "Parent" CASCADE;
DROP TABLE IF EXISTS "ParentStudent" CASCADE;
DROP TABLE IF EXISTS "Classroom" CASCADE;
DROP TABLE IF EXISTS "ClassroomTeacher" CASCADE;
DROP TABLE IF EXISTS "ClassroomStudent" CASCADE;
DROP TABLE IF EXISTS "Tag" CASCADE;
DROP TABLE IF EXISTS "StudentTag" CASCADE;
DROP TABLE IF EXISTS "Attendance" CASCADE;
DROP TABLE IF EXISTS "InboxMessage" CASCADE;
DROP TABLE IF EXISTS "StudentNote" CASCADE;
DROP TABLE IF EXISTS "TeacherComment" CASCADE;
DROP TABLE IF EXISTS "StudentFile" CASCADE;
DROP TABLE IF EXISTS "Assignment" CASCADE;
DROP TABLE IF EXISTS "AssignmentSubmission" CASCADE;
DROP TABLE IF EXISTS "AccountingEntry" CASCADE;
DROP TABLE IF EXISTS "TeacherPayroll" CASCADE;
DROP TABLE IF EXISTS "Permission" CASCADE;
DROP TABLE IF EXISTS "RolePermission" CASCADE;
DROP TABLE IF EXISTS "UserPermissionOverride" CASCADE;
DROP TABLE IF EXISTS "RefreshToken" CASCADE;
DROP TABLE IF EXISTS "SavedView" CASCADE;
DROP TABLE IF EXISTS "DashboardLayout" CASCADE;
DROP TABLE IF EXISTS "RealtimeEvent" CASCADE;
DROP TABLE IF EXISTS "mobile_devices" CASCADE;
DROP TABLE IF EXISTS "notification_preferences" CASCADE;
DROP TABLE IF EXISTS "student_daily_tasks" CASCADE;
DROP TABLE IF EXISTS "app_activity_logs" CASCADE;
DROP TABLE IF EXISTS "account_deletion_requests" CASCADE;
DROP TABLE IF EXISTS "StudySession" CASCADE;
DROP TABLE IF EXISTS "Material" CASCADE;
DROP TABLE IF EXISTS "assignment_materials" CASCADE;
DROP TABLE IF EXISTS "lesson_materials" CASCADE;
DROP TABLE IF EXISTS "AbsenceExcuse" CASCADE;
DROP TABLE IF EXISTS "StudentAcademicGoal" CASCADE;
DROP TABLE IF EXISTS "PaymentScheduleItem" CASCADE;
DROP TABLE IF EXISTS "TeacherCompensationRule" CASCADE;
DROP TABLE IF EXISTS "TeacherPayrollPeriod" CASCADE;
DROP TABLE IF EXISTS "TeacherPayrollItem" CASCADE;

ALTER TABLE "LeadSubmission" DROP COLUMN IF EXISTS "studentId";
ALTER TABLE "PurchaseIntent" DROP COLUMN IF EXISTS "studentId";
ALTER TABLE "odk_orders" DROP COLUMN IF EXISTS "user_id";
ALTER TABLE "od_orders" DROP COLUMN IF EXISTS "user_id";
ALTER TABLE "coupons" DROP COLUMN IF EXISTS "created_by_id";
ALTER TABLE "coupon_redemptions" RENAME COLUMN "user_id" TO "customer_key";
ALTER INDEX IF EXISTS "coupon_redemptions_user_id_idx" RENAME TO "coupon_redemptions_customer_key_idx";

DROP TYPE IF EXISTS "UserRole";
DROP TYPE IF EXISTS "VerificationCodeType";
DROP TYPE IF EXISTS "StudentStatus";
DROP TYPE IF EXISTS "TeacherStatus";
DROP TYPE IF EXISTS "LessonStatus";
DROP TYPE IF EXISTS "JoinEventKind";
DROP TYPE IF EXISTS "CampCategory";
DROP TYPE IF EXISTS "EnrollmentStatus";
DROP TYPE IF EXISTS "EnrollmentSource";
DROP TYPE IF EXISTS "CourseStatus";
DROP TYPE IF EXISTS "ContentType";
DROP TYPE IF EXISTS "StudentContentProgressStatus";
DROP TYPE IF EXISTS "StudentGoalStatus";
DROP TYPE IF EXISTS "AssessmentType";
DROP TYPE IF EXISTS "NotificationType";
DROP TYPE IF EXISTS "NotificationPriority";
DROP TYPE IF EXISTS "MetricPeriod";
DROP TYPE IF EXISTS "OdkExamStatus";
DROP TYPE IF EXISTS "OdkExamCadenceFamily";
DROP TYPE IF EXISTS "OdkExamFileType";
DROP TYPE IF EXISTS "OdkAccessTagGrantSource";
DROP TYPE IF EXISTS "AccessService";
DROP TYPE IF EXISTS "OdkEntitlementStatus";
DROP TYPE IF EXISTS "OdkAttemptStatus";
DROP TYPE IF EXISTS "OdkAttemptEventType";
DROP TYPE IF EXISTS "ClassroomLevel";
DROP TYPE IF EXISTS "TagColor";
DROP TYPE IF EXISTS "TagScope";
DROP TYPE IF EXISTS "AttendanceStatus";
DROP TYPE IF EXISTS "ParentRelationship";
DROP TYPE IF EXISTS "AttendanceContext";
DROP TYPE IF EXISTS "AttendanceSource";
DROP TYPE IF EXISTS "InboxCategory";
DROP TYPE IF EXISTS "InboxPriority";
DROP TYPE IF EXISTS "AssignmentStatus";
DROP TYPE IF EXISTS "SubmissionStatus";
DROP TYPE IF EXISTS "EntryType";
DROP TYPE IF EXISTS "EntryCategory";
DROP TYPE IF EXISTS "PayrollStatus";
DROP TYPE IF EXISTS "DashboardPanelKey";
DROP TYPE IF EXISTS "MobilePlatform";
DROP TYPE IF EXISTS "NotificationChannel";
DROP TYPE IF EXISTS "NotificationCategoryKey";
DROP TYPE IF EXISTS "DailyTaskSource";
DROP TYPE IF EXISTS "AccountDeletionStatus";
DROP TYPE IF EXISTS "MaterialType";
DROP TYPE IF EXISTS "MaterialVisibility";
DROP TYPE IF EXISTS "AbsenceExcuseReason";
DROP TYPE IF EXISTS "AbsenceExcuseStatus";
DROP TYPE IF EXISTS "AcademicGoalExamType";
DROP TYPE IF EXISTS "PaymentScheduleStatus";
DROP TYPE IF EXISTS "TeacherPayrollPeriodStatus";
DROP TYPE IF EXISTS "TeacherPayrollItemStatus";
