import Link from "next/link";
import { notFound } from "next/navigation";
import { BarChart3, Bot, CircleDollarSign, Inbox, Megaphone, UsersRound } from "lucide-react";
import type { BusinessPermission } from "@/lib/business/permissions";
import { requireBusinessPage } from "@/lib/business/permissions";
import { prisma } from "@/lib/prisma";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";
import { BusinessNav, BUSINESS_SECTIONS } from "@/components/business/business-nav";
import { ReplyForm } from "@/components/business/reply-form";
import { createAutomationRule, createCampaign, createFinancialTransaction, createKnowledgeEntry, createManualLead, reverseFinancialTransaction, setConversationControl, updateLeadStage } from "../actions";

export const dynamic = "force-dynamic";
const tl = new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY" });
const dt = new Intl.DateTimeFormat("tr-TR", { timeZone: "Europe/Istanbul", dateStyle: "short", timeStyle: "short" });
const labels: Record<string, string> = Object.fromEntries(BUSINESS_SECTIONS);
const permissionFor = (section: string): BusinessPermission => section === "mesaj-kutusu" ? "conversation:read" : ["gelirler", "giderler", "vergiler", "mutabakat"].includes(section) ? "finance:read" : section === "sistem-kayitlari" ? "audit:read" : section === "entegrasyonlar" || section === "ayarlar" ? "integration:write" : "dashboard:read";

function Card({ label, value, icon: Icon }: { label: string; value: string | number; icon: typeof Inbox }) { return <article className="panel-metric-card"><Icon size={18} className="text-[var(--brand-olive)]"/><p className="mt-4 text-2xl font-semibold text-[var(--site-ink)]">{value}</p><p className="mt-1 text-xs font-bold text-[var(--site-muted)]">{label}</p></article>; }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-[var(--site-line)] px-5 py-10 text-center text-sm text-[var(--site-muted)]">{text}</div>; }

export default async function BusinessSectionPage({ params, searchParams }: { params: Promise<{ section: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { section } = await params; const query = await searchParams;
  if (!labels[section]) notFound();
  const access = await requireBusinessPage(permissionFor(section)); const unitIds = access.units.map((unit) => unit.id);
  const selectedConversation = typeof query.conversation === "string" ? query.conversation : undefined;
  const [messages, conversations, leads, campaigns, ads, transactions, reconciliations, knowledge, rules, integrations, jobs, audit, aggregate] = await Promise.all([
    selectedConversation ? prisma.businessMessage.findMany({ where: { conversation: { id: selectedConversation, businessUnitId: { in: unitIds } } }, orderBy: { occurredAt: "asc" }, take: 200 }) : Promise.resolve([]),
    prisma.businessConversation.findMany({ where: { businessUnitId: { in: unitIds } }, include: { lead: true, messages: { orderBy: { occurredAt: "desc" }, take: 1 } }, orderBy: { lastMessageAt: "desc" }, take: 50 }),
    prisma.businessLead.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.businessCampaign.findMany({ where: { businessUnitId: { in: unitIds } }, include: { adSets: { include: { advertisements: true } } }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.businessAdvertisement.findMany({ where: { adSet: { campaign: { businessUnitId: { in: unitIds } } } }, include: { adSet: { include: { campaign: true } } }, take: 100 }),
    prisma.financialTransaction.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { transactionAt: "desc" }, take: 100 }),
    prisma.reconciliationRecord.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.knowledgeBaseEntry.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.automationRule.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.integrationConnection.findMany({ where: { businessUnitId: { in: unitIds } }, orderBy: { updatedAt: "desc" } }),
    prisma.backgroundJob.findMany({ where: { OR: [{ businessUnitId: { in: unitIds } }, { businessUnitId: null }] }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.auditLog.findMany({ where: { entityType: { in: ["BusinessLead", "BusinessConversation", "FinancialTransaction", "InstagramWebhookEvent"] } }, orderBy: { createdAt: "desc" }, take: 50 }),
    prisma.financialTransaction.aggregate({ where: { businessUnitId: { in: unitIds }, status: "PAID" }, _sum: { netCents: true, vatCents: true, commissionCents: true } }),
  ]);
  const income = transactions.filter((row) => row.kind !== "EXPENSE" && row.netCents > 0).reduce((sum, row) => sum + row.netCents, 0);
  const expense = transactions.filter((row) => row.kind === "EXPENSE" || row.netCents < 0).reduce((sum, row) => sum + Math.abs(row.netCents), 0);
  const selected = conversations.find((item) => item.id === selectedConversation);

  return <PanelShell role={access.session.role} fullName={access.session.fullName} email={access.session.email} nav={<PanelNav role={access.session.role} />}>
    <header className="mb-5"><p className="text-[11px] font-extrabold uppercase tracking-[.1em] text-[var(--brand-olive)]">Reklam, CRM ve Finans</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em] text-[var(--site-ink)]">{labels[section]}</h1><p className="mt-2 text-sm text-[var(--site-muted)]">{access.units.map((unit) => unit.name).join(" · ")} · Europe/Istanbul</p></header>
    <BusinessNav active={section}/>
    <div className="mt-5">
      {section === "genel-bakis" && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="Konuşma" value={conversations.length} icon={Inbox}/><Card label="Yeni aday" value={leads.filter((x) => x.stage === "NEW").length} icon={UsersRound}/><Card label="Satış" value={leads.filter((x) => x.stage === "WON").length} icon={BarChart3}/><Card label="Reklam harcaması" value={tl.format(campaigns.reduce((s,x)=>s+x.spentCents,0)/100)} icon={Megaphone}/><Card label="Net gelir" value={tl.format((aggregate._sum.netCents ?? 0)/100)} icon={CircleDollarSign}/><Card label="İnsan bekleyen" value={conversations.filter((x)=>x.status === "WAITING_HUMAN").length} icon={Bot}/></section><section className="panel-surface mt-5 p-5"><h2 className="text-sm font-extrabold">Operasyon özeti</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><p className="rounded-xl bg-emerald-50 p-4 text-sm">Gelir <strong className="block text-lg">{tl.format(income/100)}</strong></p><p className="rounded-xl bg-rose-50 p-4 text-sm">Gider <strong className="block text-lg">{tl.format(expense/100)}</strong></p><p className="rounded-xl bg-amber-50 p-4 text-sm">Tahmini net <strong className="block text-lg">{tl.format((income-expense)/100)}</strong></p></div></section></>}

      {section === "mesaj-kutusu" && <div className="grid gap-4 xl:grid-cols-[360px_1fr]"><section className="panel-surface divide-y divide-[var(--site-line)] overflow-hidden">{conversations.length ? conversations.map((c)=><Link key={c.id} href={`?conversation=${c.id}`} className={`block p-4 hover:bg-[var(--site-bg-warm)] ${selectedConversation===c.id?"bg-[var(--brand-olive-soft)]":""}`}><div className="flex justify-between gap-3"><strong className="truncate text-sm">{c.displayName||c.username||c.instagramScopedUserId}</strong><time className="text-[10px] text-[var(--site-muted)]">{dt.format(c.lastMessageAt)}</time></div><p className="mt-1 truncate text-xs text-[var(--site-muted)]">{c.messages[0]?.body||"Medya mesajı"}</p><div className="mt-2 flex gap-1 text-[9px] font-bold"><span className="rounded-full bg-white px-2 py-1">{c.status}</span><span className="rounded-full bg-white px-2 py-1">AI {c.aiMode}</span>{c.unreadCount?<span className="rounded-full bg-rose-600 px-2 py-1 text-white">{c.unreadCount}</span>:null}</div></Link>):<Empty text="Henüz konuşma yok."/>}</section><section className="panel-surface p-5">{selected?<><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-extrabold">{selected.displayName||selected.instagramScopedUserId}</h2><p className="text-xs text-[var(--site-muted)]">{selected.temperature} · {selected.productInterest}</p></div><form action={setConversationControl} className="flex gap-2"><input type="hidden" name="id" value={selected.id}/><select name="aiMode" defaultValue={selected.aiMode} className="rounded-xl border px-2 py-1 text-xs"><option>OFF</option><option>SUGGESTION</option><option>AUTO_SAFE</option><option>AUTO</option></select><select name="status" defaultValue={selected.status} className="rounded-xl border px-2 py-1 text-xs"><option>OPEN</option><option>WAITING_HUMAN</option><option>CLOSED</option><option>SPAM</option></select><button className="rounded-xl border px-3 text-xs font-bold">Kaydet</button></form></div><div className="mt-5 max-h-[520px] space-y-3 overflow-auto">{messages.map((m)=><article key={m.id} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm ${m.direction==="OUTBOUND"?"ml-auto bg-[var(--brand-olive)] text-white":"bg-[var(--site-bg-warm)]"}`}><p>{m.body||"Medya"}</p><p className="mt-1 text-[9px] opacity-70">{m.senderType} · {m.status} · {dt.format(m.occurredAt)}</p></article>)}</div><ReplyForm conversationId={selected.id}/></>:<Empty text="Detay için bir konuşma seçin."/>}</section></div>}

      {section === "adaylar" && <><form action={createManualLead} className="panel-surface mb-4 grid gap-3 p-4 sm:grid-cols-5"><input name="firstName" required placeholder="Ad" className="rounded-xl border px-3 py-2 text-sm"/><input name="phone" placeholder="Telefon" className="rounded-xl border px-3 py-2 text-sm"/><input name="email" type="email" placeholder="E-posta" className="rounded-xl border px-3 py-2 text-sm"/><select name="productInterest" className="rounded-xl border px-3 py-2 text-sm"><option value="UNKNOWN">Ürün bilinmiyor</option><option value="ONLINE_DERSHANEM">OnlineDershanem</option><option value="ONLINE_DENEME_KULUBU">Deneme Kulübü</option></select><button className="rounded-xl bg-[var(--brand-olive)] px-3 py-2 text-sm font-bold text-white">Aday ekle</button></form><LeadTable leads={leads}/></>}
      {section === "satis-hunisi" && <div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5">{["NEW","CONTACTED","QUALIFIED","OFFER_SENT","WON"].map((stage)=><section key={stage} className="panel-surface p-3"><h2 className="mb-3 text-xs font-extrabold">{stage} · {leads.filter(x=>x.stage===stage).length}</h2>{leads.filter(x=>x.stage===stage).map((lead)=><form action={updateLeadStage} key={lead.id} className="mb-2 rounded-xl border bg-white p-3"><input type="hidden" name="id" value={lead.id}/><p className="truncate text-xs font-bold">{lead.firstName||lead.instagramScopedId||"Adsız"}</p><select name="stage" defaultValue={lead.stage} className="mt-2 w-full rounded-lg border p-1 text-[10px]"><option>NEW</option><option>CONTACTED</option><option>QUALIFIED</option><option>MEETING_PLANNED</option><option>TRIAL_PLANNED</option><option>OFFER_SENT</option><option>PAYMENT_PENDING</option><option>WON</option><option>LOST</option><option>SPAM</option></select><button className="mt-2 text-[10px] font-bold text-[var(--brand-olive)]">Aşamayı kaydet</button></form>)}</section>)}</div>}
      {(section === "kampanyalar" || section === "reklamlar") && <>{section === "kampanyalar"?<form action={createCampaign} className="panel-surface mb-4 grid gap-3 p-4 sm:grid-cols-5"><input aria-label="Kampanya adı" name="name" required placeholder="Kampanya adı" className="rounded-xl border px-3 py-2 text-sm"/><input aria-label="Platform" name="platform" defaultValue="INSTAGRAM" className="rounded-xl border px-3 py-2 text-sm"/><input aria-label="Bütçe TL" name="budgetTl" type="number" min="0" step="0.01" placeholder="Bütçe TL" className="rounded-xl border px-3 py-2 text-sm"/><select aria-label="Ürün" name="productInterest" className="rounded-xl border px-3 py-2 text-sm"><option>UNKNOWN</option><option>ONLINE_DERSHANEM</option><option>ONLINE_DENEME_KULUBU</option></select><button className="rounded-xl bg-[var(--brand-olive)] text-sm font-bold text-white">Kampanya ekle</button></form>:null}<DataTable headers={["Ad","Kampanya","Harcama","Gösterim","Tıklama","Lead","Satış","Gelir"]} rows={(section === "reklamlar"?ads:campaigns.flatMap(c=>c.adSets.flatMap(s=>s.advertisements.map(a=>({...a,adSet:{...s,campaign:c}}))))).map((a)=><tr key={a.id} className="border-t"><td className="p-3 font-bold">{a.name}</td><td className="p-3">{a.adSet.campaign.name}</td><td className="p-3">{tl.format(a.spentCents/100)}</td><td className="p-3">{a.impressions}</td><td className="p-3">{a.clicks}</td><td className="p-3">{a.leadCount}</td><td className="p-3">{a.saleCount}</td><td className="p-3">{tl.format(a.revenueCents/100)}</td></tr>)}/></>}
      {(section === "gelirler" || section === "giderler") && <><form action={createFinancialTransaction} className="panel-surface mb-4 grid gap-3 p-4 sm:grid-cols-5"><select name="kind" defaultValue={section === "giderler" ? "EXPENSE" : "MANUAL_INCOME"} className="rounded-xl border px-3 py-2 text-sm"><option>MANUAL_INCOME</option><option>EXPENSE</option><option>ADJUSTMENT</option></select><input name="description" required placeholder="Açıklama" className="rounded-xl border px-3 py-2 text-sm"/><input name="category" required placeholder="Kategori" className="rounded-xl border px-3 py-2 text-sm"/><input name="amountTl" type="number" step="0.01" min="0.01" required placeholder="Tutar TL" className="rounded-xl border px-3 py-2 text-sm"/><button className="rounded-xl bg-[var(--brand-olive)] text-sm font-bold text-white">Kaydet</button></form><TransactionTable rows={transactions.filter((x)=>section==="giderler"?x.kind==="EXPENSE":x.kind!=="EXPENSE")}/></>}
      {section === "vergiler" && <><div role="note" className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Bu ekran operasyonel takip ve tahmini raporlama amaçlıdır. Resmî beyan ve muhasebe işlemleri için mali müşavir kontrolü gerekir.</div><section className="grid gap-3 sm:grid-cols-3"><Card label="Hesaplanan KDV" value={tl.format((aggregate._sum.vatCents??0)/100)} icon={CircleDollarSign}/><Card label="Komisyon" value={tl.format((aggregate._sum.commissionCents??0)/100)} icon={CircleDollarSign}/><Card label="Tahmini net kâr" value={tl.format((income-expense-(aggregate._sum.vatCents??0))/100)} icon={BarChart3}/></section></>}
      {section === "mutabakat" && (reconciliations.length?<DataTable headers={["Sağlayıcı","Dış ID","Beklenen","Gerçek","Durum"]} rows={reconciliations.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.provider}</td><td className="p-3">{x.externalId||"—"}</td><td className="p-3">{tl.format((x.expectedCents||0)/100)}</td><td className="p-3">{tl.format((x.actualCents||0)/100)}</td><td className="p-3 font-bold">{x.status}</td></tr>)}/>:<Empty text="Mutabakat sorunu yok."/>)}
      {section === "raporlar" && <section className="panel-surface p-5"><h2 className="font-extrabold">Dışa aktarma</h2><p className="mt-2 text-sm text-[var(--site-muted)]">Tüm hücreler CSV formula injection korumasıyla hazırlanır.</p><Link href="/api/admin/business/reports.csv" className="mt-4 inline-flex rounded-xl bg-[var(--brand-olive)] px-4 py-2 text-xs font-bold text-white">CSV indir</Link></section>}
      {section === "ai-bilgi-merkezi" && <><form action={createKnowledgeEntry} className="panel-surface mb-4 grid gap-3 p-4 sm:grid-cols-4"><input aria-label="Başlık" name="title" required placeholder="Başlık" className="rounded-xl border px-3 py-2 text-sm"/><input aria-label="Kategori" name="category" required placeholder="Kategori" className="rounded-xl border px-3 py-2 text-sm"/><select aria-label="Ürün" name="productInterest" className="rounded-xl border px-3 py-2 text-sm"><option>UNKNOWN</option><option>ONLINE_DERSHANEM</option><option>ONLINE_DENEME_KULUBU</option></select><textarea aria-label="İçerik" name="content" required placeholder="Doğrulanmış içerik" className="min-h-24 rounded-xl border px-3 py-2 text-sm sm:col-span-3"/><button className="rounded-xl bg-[var(--brand-olive)] text-sm font-bold text-white">Bilgi ekle</button></form>{knowledge.length?<div className="grid gap-3 md:grid-cols-2">{knowledge.map(x=><article key={x.id} className="panel-surface p-4"><div className="flex justify-between"><strong>{x.title}</strong><span className="text-[10px]">v{x.version} · {x.isActive?"Aktif":"Pasif"}</span></div><p className="mt-2 line-clamp-4 text-sm text-[var(--site-body)]">{x.content}</p><p className="mt-2 text-[10px] text-[var(--site-muted)]">{x.category} · {x.source||"Manuel"}</p></article>)}</div>:<Empty text="Bilgi merkezi kaydı yok."/>}</>}
      {section === "otomasyon-kurallari" && <><form action={createAutomationRule} className="panel-surface mb-4 grid gap-3 p-4 sm:grid-cols-4"><input aria-label="Kural adı" name="name" required placeholder="Kural adı" className="rounded-xl border px-3 py-2 text-sm"/><select aria-label="Tetikleyici" name="triggerType" className="rounded-xl border px-3 py-2 text-sm"><option>NEW_MESSAGE</option><option>HOT_LEAD</option><option>PAYMENT_COMPLETED</option><option>COMPLAINT</option><option>UNANSWERED_HOT_LEAD</option></select><select aria-label="Aksiyon" name="actionType" className="rounded-xl border px-3 py-2 text-sm"><option>SUGGEST_AI_REPLY</option><option>ASSIGN_SALES</option><option>MARK_WON</option><option>NOTIFY_ADMIN</option><option>ADD_TAG</option></select><button className="rounded-xl bg-[var(--brand-olive)] text-sm font-bold text-white">Kural ekle</button></form>{rules.length?<div className="space-y-3">{rules.map(x=><article key={x.id} className="panel-surface flex justify-between p-4"><div><strong>{x.name}</strong><p className="text-xs text-[var(--site-muted)]">{x.triggerType}</p></div><span className="text-xs font-bold">{x.isActive?"Aktif":"Pasif"}</span></article>)}</div>:<Empty text="Otomasyon kuralı yok."/>}</>}
      {section === "entegrasyonlar" && <div className="grid gap-3 md:grid-cols-2">{["INSTAGRAM","OPENAI","META_ADS","EMAIL"].map(provider=>{const item=integrations.find(x=>x.provider===provider);return <article key={provider} className="panel-surface p-5"><strong>{provider}</strong><p className="mt-2 text-sm">{item?.status||"DISCONNECTED"}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Secret değerleri yalnız sunucu ortamından okunur.</p></article>})}</div>}
      {section === "sistem-kayitlari" && <div className="grid gap-4 xl:grid-cols-2"><section className="panel-surface p-4"><h2 className="mb-3 font-extrabold">Arka plan işleri</h2>{jobs.map(x=><p key={x.id} className="border-t py-2 text-xs"><strong>{x.type}</strong> · {x.status} · deneme {x.attempts}/{x.maxAttempts}</p>)}</section><section className="panel-surface p-4"><h2 className="mb-3 font-extrabold">Audit kayıtları</h2>{audit.map(x=><p key={x.id} className="border-t py-2 text-xs"><strong>{x.action}</strong> · {x.entityType} · {dt.format(x.createdAt)}</p>)}</section></div>}
      {section === "ayarlar" && <section className="panel-surface p-5"><h2 className="font-extrabold">Güvenli varsayılanlar</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-[var(--site-body)]"><li>AI başlangıç modu: SUGGESTION</li><li>Mesaj saklama ve anonimleştirme operasyon runbook’unda tanımlıdır.</li><li>Finans kayıtları hard delete edilmez; ters kayıt kullanılır.</li><li>Entegrasyon anahtarları istemciye gönderilmez.</li></ul></section>}
    </div>
  </PanelShell>;
}

function DataTable({ headers, rows }: { headers: string[]; rows: React.ReactNode[] }) { return rows.length?<div className="panel-surface overflow-x-auto"><table className="w-full min-w-[720px] text-left text-xs"><thead><tr>{headers.map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>:<Empty text="Kayıt bulunmuyor."/>; }
function LeadTable({ leads }: { leads: Awaited<ReturnType<typeof prisma.businessLead.findMany>> }) { return <DataTable headers={["Aday","Kaynak","Ürün","Sıcaklık","Aşama","Son temas"]} rows={leads.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-bold">{x.firstName||x.instagramScopedId||"Adsız"}</td><td className="p-3">{x.source}</td><td className="p-3">{x.productInterest}</td><td className="p-3">{x.temperature}</td><td className="p-3">{x.stage}</td><td className="p-3">{dt.format(x.lastContactAt)}</td></tr>)}/>; }
function TransactionTable({ rows }: { rows: Awaited<ReturnType<typeof prisma.financialTransaction.findMany>> }) { return <DataTable headers={["Tarih","Açıklama","Kaynak","Kategori","Net","Vergi","Durum","İşlem"]} rows={rows.map(x=><tr key={x.id} className="border-t"><td className="p-3">{dt.format(x.transactionAt)}</td><td className="p-3 font-bold">{x.description}</td><td className="p-3">{x.source}</td><td className="p-3">{x.category}</td><td className="p-3">{tl.format(x.netCents/100)}</td><td className="p-3">{tl.format(x.vatCents/100)}</td><td className="p-3">{x.status}</td><td className="p-3">{!x.cancelledAt?<form action={reverseFinancialTransaction}><input type="hidden" name="id" value={x.id}/><button className="text-rose-700 underline">Ters kayıt</button></form>:"İptal"}</td></tr>)}/>; }
