"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, FileUp, LockKeyhole, Save, Send } from "lucide-react";

type Outcome = { id: string; label: string };
type Question = { id: string; questionNumber: number; correctOption: "A" | "B" | "C" | "D" | "E" | null; difficulty: "EASY" | "MEDIUM" | "HARD"; bookletPage: number | null; outcomeIds: string[]; primaryOutcomeId: string | null };
type Issue = { level: "error" | "warning"; code: string; message: string; questionNumber?: number };
type Props = { exam: { id: string; title: string; family: string; status: string; startsAt: string; endsAt: string; lateEntryMinutes: number; meetRequired: boolean; meetUrl: string; versionStatus: string; durationMinutes: number; files: { id: string; type: string; fileName: string }[]; questions: Question[] }; outcomes: Outcome[]; issues: Issue[]; resultStats: { attemptCount: number; submittedCount: number; scoredCount: number; examEnded: boolean } };

export function AdminExamEditor({ exam, outcomes, issues, resultStats }: Props) {
  const router = useRouter(); const editable = exam.status === "DRAFT" && exam.versionStatus === "DRAFT"; const [questions, setQuestions] = useState(exam.questions); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function json(url: string, method: string, body?: unknown) { setBusy(url); setMessage(""); const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json().catch(() => ({})); setBusy(""); if (!response.ok) { setMessage(result.error || "İşlem tamamlanamadı."); return null; } setMessage("Kaydedildi."); router.refresh(); return result; }
  async function saveQuestions() { await json(`/api/odk/admin/exams/${exam.id}/questions`, "PUT", { questions }); }
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy("upload"); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/odk/admin/exams/${exam.id}/files`, { method: "POST", body: form }); const result = await response.json().catch(() => ({})); setBusy(""); if (!response.ok) return setMessage(result.error || "PDF yüklenemedi."); setMessage("PDF private depoya yüklendi."); router.refresh(); }
  return <div className="space-y-6">
    <section className="panel-surface p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-extrabold">1. Planlama bilgileri</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Saatler tarayıcınızın yerel saatine göre girilir.</p></div><span className="rounded-full bg-[var(--brand-olive-soft)] px-3 py-1.5 text-[10px] font-extrabold">{exam.status}</span></div><form className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3" onSubmit={async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const starts = String(data.get("startsAt") || ""); const ends = String(data.get("endsAt") || ""); await json(`/api/odk/admin/exams/${exam.id}`, "PATCH", { title: data.get("title"), startsAt: starts ? new Date(starts).toISOString() : null, endsAt: ends ? new Date(ends).toISOString() : null, lateEntryMinutes: Number(data.get("lateEntryMinutes")), meetRequired: data.get("meetRequired") === "on", meetUrl: data.get("meetUrl") || null }); }}><input name="title" defaultValue={exam.title} required className="panel-input" disabled={!editable && exam.status !== "READY"} /><input name="startsAt" type="datetime-local" defaultValue={exam.startsAt} className="panel-input" disabled={exam.status !== "DRAFT" && exam.status !== "READY"} /><input name="endsAt" type="datetime-local" defaultValue={exam.endsAt} className="panel-input" disabled={exam.status !== "DRAFT" && exam.status !== "READY"} /><input name="lateEntryMinutes" type="number" min={0} max={120} defaultValue={exam.lateEntryMinutes} className="panel-input" disabled={exam.status !== "DRAFT" && exam.status !== "READY"} /><input name="meetUrl" type="url" placeholder="https://meet.google.com/..." defaultValue={exam.meetUrl} className="panel-input" disabled={exam.status !== "DRAFT" && exam.status !== "READY"} /><label className="inline-flex items-center gap-2 text-xs font-bold"><input name="meetRequired" type="checkbox" defaultChecked={exam.meetRequired} disabled={exam.status !== "DRAFT" && exam.status !== "READY"} /> Meet zorunlu</label>{exam.status === "DRAFT" || exam.status === "READY" ? <button className="panel-primary-button md:col-span-2 xl:col-span-3"><Save size={14} /> Planı kaydet</button> : null}</form></section>

    <section className="panel-surface p-5"><h2 className="text-sm font-extrabold">2. Private PDF dosyaları</h2><div className="mt-3 flex flex-wrap gap-2">{exam.files.map((file) => <a key={file.id} href={`/api/odk/admin/files/${file.id}`} target="_blank" rel="noreferrer" className="panel-quick-action">{file.type === "BOOKLET_PDF" ? "Kitapçık" : "Cevap anahtarı"}: {file.fileName}</a>)}</div>{editable ? <form className="mt-4 flex flex-wrap items-center gap-3" onSubmit={(event) => void upload(event)}><select name="type" className="panel-input"><option value="BOOKLET_PDF">Öğrenci kitapçığı</option><option value="ANSWER_KEY_PDF">Cevap anahtarı PDF</option></select><input name="file" type="file" accept="application/pdf,.pdf" required className="text-xs" /><button disabled={busy === "upload"} className="panel-primary-button"><FileUp size={14} /> PDF yükle</button></form> : null}</section>

    <section className="panel-surface p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-sm font-extrabold">3. Cevaplar ve kazanımlar</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Her soruya doğru cevap ve tam bir ana kazanım girin.</p></div>{editable ? <button type="button" onClick={() => void saveQuestions()} disabled={Boolean(busy)} className="panel-primary-button"><Save size={14} /> Soruları kaydet</button> : null}</div><div className="mt-4 overflow-x-auto"><table className="min-w-[820px] w-full text-xs"><thead><tr className="text-left text-[10px] uppercase text-[var(--site-muted)]"><th className="pb-2">Soru</th><th>Cevap</th><th>Zorluk</th><th>PDF sayfa</th><th>Ana kazanım</th></tr></thead><tbody>{questions.map((question, index) => <tr key={question.id} className="border-t border-[var(--site-line)]"><th className="py-2 text-left">{question.questionNumber}</th><td><select aria-label={`Soru ${question.questionNumber} cevap`} disabled={!editable} className="panel-input py-2" value={question.correctOption || ""} onChange={(event) => setQuestions((current) => current.map((item, i) => i === index ? { ...item, correctOption: (event.target.value || null) as Question["correctOption"] } : item))}><option value="">—</option>{["A","B","C","D","E"].map((option) => <option key={option}>{option}</option>)}</select></td><td><select disabled={!editable} className="panel-input py-2" value={question.difficulty} onChange={(event) => setQuestions((current) => current.map((item, i) => i === index ? { ...item, difficulty: event.target.value as Question["difficulty"] } : item))}><option value="EASY">Kolay</option><option value="MEDIUM">Orta</option><option value="HARD">Zor</option></select></td><td><input disabled={!editable} className="panel-input w-20 py-2" type="number" min={1} value={question.bookletPage || ""} onChange={(event) => setQuestions((current) => current.map((item, i) => i === index ? { ...item, bookletPage: Number(event.target.value) || null } : item))} /></td><td><select disabled={!editable} className="panel-input min-w-80 py-2" value={question.primaryOutcomeId || ""} onChange={(event) => { const primary = event.target.value || null; setQuestions((current) => current.map((item, i) => i === index ? { ...item, primaryOutcomeId: primary, outcomeIds: primary ? [...new Set([...item.outcomeIds, primary])] : item.outcomeIds } : item)); }}><option value="">Kazanım seçin</option>{outcomes.map((outcome) => <option key={outcome.id} value={outcome.id}>{outcome.label}</option>)}</select></td></tr>)}</tbody></table></div>{!outcomes.length ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900">Bu sınav türü için aktif matematik kazanımı bulunamadı. Önce OD kazanım yönetiminden müfredatı etkinleştirin.</p> : null}</section>

    <section className="panel-surface p-5"><h2 className="text-sm font-extrabold">4. Yayın kontrolleri</h2><div className="mt-3 space-y-2">{issues.map((issue, index) => <p key={`${issue.code}-${index}`} className={`rounded-xl p-3 text-xs font-bold ${issue.level === "error" ? "bg-rose-50 text-rose-800" : "bg-amber-50 text-amber-900"}`}>{issue.questionNumber ? `Soru ${issue.questionNumber}: ` : ""}{issue.message}</p>)}{!issues.length ? <p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-800"><CheckCircle2 size={15} /> Sürüm kilitlenmeye hazır.</p> : null}</div><div className="mt-4 flex flex-wrap gap-3">{exam.status === "DRAFT" ? <button type="button" disabled={issues.some((issue) => issue.level === "error") || Boolean(busy)} onClick={() => void json(`/api/odk/admin/exams/${exam.id}/ready`, "POST")} className="panel-primary-button"><LockKeyhole size={14} /> Sürümü kilitle ve hazırla</button> : null}{exam.status === "READY" ? <button type="button" disabled={Boolean(busy)} onClick={() => void json(`/api/odk/admin/exams/${exam.id}/schedule`, "POST")} className="panel-primary-button"><Send size={14} /> Denemeyi planla</button> : null}</div>{message ? <p role="status" className="mt-3 text-xs font-bold text-[var(--brand-olive)]">{message}</p> : null}</section>

    <section className="panel-surface p-5"><h2 className="text-sm font-extrabold">5. Puanlama ve sonuç açıklama</h2><p className="mt-1 text-xs leading-5 text-[var(--site-muted)]">Sonuçlar önce hesaplanır ve kontrol altında tutulur. Öğrenci ancak ayrıca açıkladığınızda görebilir.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Katılım", resultStats.attemptCount], ["Teslim", resultStats.submittedCount], ["Puanlandı", resultStats.scoredCount]].map(([label, value]) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><p className="text-xl font-black text-[var(--site-ink)]">{value}</p><p className="mt-1 text-xs text-[var(--site-muted)]">{label}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-3">{["SCHEDULED", "LIVE", "ENDED"].includes(exam.status) ? <button type="button" disabled={!resultStats.examEnded || Boolean(busy)} onClick={() => void json(`/api/odk/admin/exams/${exam.id}/score`, "POST")} className="panel-primary-button"><CheckCircle2 size={14} /> Teslimleri puanla</button> : null}{exam.status === "SCORED" ? <button type="button" disabled={resultStats.submittedCount !== resultStats.scoredCount || Boolean(busy)} onClick={() => { if (window.confirm("Sonuçlar ve cevap anahtarı öğrencilere açılacak. Devam edilsin mi?")) void json(`/api/odk/admin/exams/${exam.id}/release`, "POST"); }} className="panel-primary-button"><Send size={14} /> Sonuçları açıkla</button> : null}{exam.status === "RELEASED" ? <span className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-2.5 text-xs font-extrabold text-emerald-800"><CheckCircle2 size={14} /> Sonuçlar açıklandı</span> : null}</div>{!resultStats.examEnded && ["SCHEDULED", "LIVE"].includes(exam.status) ? <p className="mt-3 text-xs font-bold text-amber-700">Puanlama sınavın genel bitiş saatinden sonra açılır.</p> : null}</section>
  </div>;
}
