import Link from "next/link";
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BookOpenCheck, ShieldCheck, Target } from "lucide-react";

type Student = { userId: string; name: string; context: string };
type Report = { student: { userId: string; name: string }; exams: Array<{ id: string; title: string; family: string; takenAt: Date; correctCount: number; wrongCount: number; blankCount: number; totalNet: number }>; trends: Array<{ outcomeId: string; code: string; title: string; unitName: string; latestAccuracy: number; previousAccuracy: number | null; delta: number | null; evidenceCount: number; questionCount: number }> };
const date = new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeZone: "Europe/Istanbul" });

function trendCopy(delta: number | null) {
  if (delta === null) return { label: "İlk ölçüm", Icon: ArrowRight, className: "bg-slate-100 text-slate-600" };
  if (delta >= 10) return { label: `+${delta.toFixed(0)} puan`, Icon: ArrowUpRight, className: "bg-emerald-50 text-emerald-700" };
  if (delta <= -10) return { label: `${delta.toFixed(0)} puan`, Icon: ArrowDownRight, className: "bg-amber-50 text-amber-800" };
  return { label: "Benzer düzey", Icon: ArrowRight, className: "bg-slate-100 text-slate-600" };
}

export function OdkAudienceReports({ role, basePath, students, selectedUserId, report }: { role: "ADMIN" | "TEACHER" | "PARENT"; basePath: string; students: Student[]; selectedUserId: string | null; report: Report | null }) {
  const latest = report?.exams.at(-1) || null;
  return <>
    <header><p className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.09em] text-[var(--brand-olive)]"><ShieldCheck size={15} /> {role === "ADMIN" ? "ODK öğrenci raporları" : role === "TEACHER" ? "Yalnız sorumlu olduğunuz öğrenciler" : "Yalnız bağlı öğrenciniz"}</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.05em] text-[var(--site-ink)]">Matematik denemelerini öğrenme kararına dönüştürün.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-[var(--site-body)]">Sonuçlar yalnız admin tarafından açıklandıktan sonra görünür. Eğilimler öğrencinin kendi önceki ölçümüyle karşılaştırılır; öğrenci sıralaması yapılmaz.</p></header>
    {!students.length ? <div className="mt-8 rounded-3xl border border-dashed border-[var(--site-border)] bg-white p-8 text-center text-sm text-[var(--site-muted)]">{role === "ADMIN" ? "Henüz denemeye katılmış ODK öğrencisi yok." : role === "TEACHER" ? "Aktif grubunuza bağlı öğrenci bulunmuyor." : "Henüz bağlı öğrenciniz bulunmuyor."}</div> : <>
      <nav aria-label="Öğrenci seçimi" className="mt-7 flex gap-2 overflow-x-auto pb-2">{students.map((student) => <Link key={student.userId} href={`${basePath}?ogrenci=${student.userId}`} className={`min-w-fit rounded-2xl border px-4 py-3 ${student.userId === selectedUserId ? "border-[var(--brand-olive)] bg-[var(--brand-olive)] text-white" : "border-[var(--site-border)] bg-white text-[var(--site-ink)]"}`}><strong className="block text-sm">{student.name}</strong><span className={`mt-1 block text-[10px] ${student.userId === selectedUserId ? "text-white/75" : "text-[var(--site-muted)]"}`}>{student.context}</span></Link>)}</nav>
      {!report || !latest ? <div className="mt-6 rounded-3xl border border-dashed border-[var(--site-border)] bg-white p-8"><h2 className="font-extrabold text-[var(--site-ink)]">Açıklanmış sonuç henüz yok.</h2><p className="mt-2 text-sm leading-6 text-[var(--site-muted)]">Öğrenci denemeyi tamamlayıp admin sonucu açıkladığında rapor burada oluşacak.</p></div> : <>
        <section className="mt-6 rounded-3xl border border-[var(--site-border)] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase text-[var(--brand-olive)]">Son açıklanan deneme</p><h2 className="mt-2 text-xl font-semibold text-[var(--site-ink)]">{latest.title}</h2><p className="mt-1 text-xs text-[var(--site-muted)]">{latest.family} · {date.format(latest.takenAt)}</p></div><span className="rounded-2xl bg-[var(--panel-nav-active)] px-4 py-3 text-center"><strong className="block text-2xl font-black text-[var(--site-ink)]">{latest.totalNet.toFixed(2)}</strong><span className="text-[10px] font-bold text-[var(--site-muted)]">net</span></span></div><div className="mt-5 grid grid-cols-3 gap-3">{[["Doğru", latest.correctCount, "text-emerald-700"], ["Yanlış", latest.wrongCount, "text-rose-700"], ["Boş", latest.blankCount, "text-slate-600"]].map(([label, value, color]) => <div key={String(label)} className="rounded-2xl bg-slate-50 p-3 text-center"><strong className={`block text-lg ${color}`}>{value}</strong><span className="text-[10px] text-[var(--site-muted)]">{label}</span></div>)}</div></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><div className="panel-surface p-5"><div className="flex items-start gap-3"><Target size={18} className="mt-0.5 text-[var(--brand-olive)]" /><div><h2 className="font-extrabold text-[var(--site-ink)]">Kazanım eğilimleri</h2><p className="mt-1 text-xs leading-5 text-[var(--site-muted)]">Yüzde, bu kazanıma bağlı sorulardaki doğru oranıdır. Az sorulu ölçümlerde karar vermeden yeni kanıt bekleyin.</p></div></div><div className="mt-4 space-y-3">{report.trends.map((trend) => { const copy = trendCopy(trend.delta); return <article key={trend.outcomeId} className="rounded-2xl border border-[var(--site-border)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black text-[var(--brand-olive)]">{trend.code} · {trend.unitName}</p><h3 className="mt-1 text-sm font-bold leading-5 text-[var(--site-ink)]">{trend.title}</h3></div><span className="text-lg font-black text-[var(--site-ink)]">%{trend.latestAccuracy.toFixed(0)}</span></div><div className="mt-3 flex flex-wrap items-center gap-2"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-extrabold ${copy.className}`}><copy.Icon size={12} /> {copy.label}</span><span className="text-[10px] text-[var(--site-muted)]">{trend.evidenceCount} deneme · {trend.questionCount} soru</span>{trend.questionCount < 3 ? <span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-bold text-amber-800">Sınırlı kanıt</span> : null}</div></article>; })}{!report.trends.length ? <p className="text-sm text-[var(--site-muted)]">Kazanım verisi bulunmuyor.</p> : null}</div></div>
        <div className="panel-surface p-5"><div className="flex items-center gap-2"><BarChart3 size={17} className="text-[var(--brand-olive)]" /><h2 className="font-extrabold text-[var(--site-ink)]">Deneme geçmişi</h2></div><div className="mt-4 space-y-3">{[...report.exams].reverse().map((exam) => <article key={exam.id} className="rounded-2xl border border-[var(--site-border)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold text-[var(--site-ink)]">{exam.title}</h3><p className="mt-1 text-[10px] text-[var(--site-muted)]">{exam.family} · {date.format(exam.takenAt)}</p></div><strong className="text-lg text-[var(--brand-olive)]">{exam.totalNet.toFixed(2)}</strong></div><p className="mt-3 text-xs text-[var(--site-body)]">{exam.correctCount} doğru · {exam.wrongCount} yanlış · {exam.blankCount} boş</p></article>)}</div><div className="mt-5 rounded-2xl bg-[var(--panel-nav-active)] p-4"><h3 className="flex items-center gap-2 text-xs font-extrabold text-[var(--site-ink)]"><BookOpenCheck size={14} /> Yorumlama notu</h3><p className="mt-2 text-xs leading-5 text-[var(--site-body)]">Tek bir denemeyi kesin yargı olarak kullanmayın. Tekrarlayan kazanım kanıtı ve öğrencinin kendi eğilimi daha anlamlıdır.</p></div></div></section>
      </>}
    </>}
  </>;
}
