import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { OrderLinkForm } from "@/components/panel/order-link-form";
import { AdminPageHeader } from "@/components/panel/admin-page-header";
import { Activity, CreditCard, MailWarning } from "lucide-react";
import { LeadStatusControl } from "@/components/panel/lead-status-control";
import { EmailRetryButton } from "@/components/panel/email-retry-button";
import { evaluateCronHeartbeats } from "@/lib/jobs/health";
import { getOdLifecycleQueue } from "@/lib/od/lifecycle-queue-server";
import { OdLifecycleQueueSection } from "@/components/panel/od-lifecycle-queue";
import { calculateOdPlacementMetrics } from "@/lib/od/placement";

export const dynamic = "force-dynamic";

export default async function OperationsPage() {
  const session = await requireRole("ADMIN");
  const [orders, lifecycle, leads, studentsRaw, staffRaw, emailQueue, cronHeartbeats, placementTransitions] = await Promise.all([
    prisma.odOrder.findMany({ orderBy: { createdAt: "desc" }, take: 30, include: { user: { select: { fullName: true, email: true } } } }),
    getOdLifecycleQueue(),
    prisma.leadSubmission.findMany({ orderBy: { submittedAt: "desc" }, take: 30 }),
    prisma.user.findMany({ where: { role: "STUDENT", status: "ACTIVE" }, orderBy: { fullName: "asc" }, select: { id: true, fullName: true, email: true } }),
    prisma.user.findMany({ where: { role: { in: ["ADMIN", "TEACHER"] }, status: "ACTIVE" }, orderBy: { fullName: "asc" }, select: { id: true, fullName: true, email: true } }),
    prisma.emailOutbox.findMany({ where: { status: { not: "SENT" } }, orderBy: { createdAt: "desc" }, take: 20, select: { id: true, subject: true, status: true, attempts: true, createdAt: true } }),
    prisma.cronHeartbeat.findMany(),
    prisma.odOnboardingTransition.findMany({ where: { occurredAt: { gte: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000) } }, select: { onboardingId: true, toState: true, occurredAt: true } }),
  ]);
  const students = studentsRaw.map((student) => ({ id: student.id, name: student.fullName || student.email }));
  const staff = staffRaw.map((person) => ({ id: person.id, name: person.fullName || person.email }));
  const cronHealth = evaluateCronHeartbeats(cronHeartbeats);
  const placementMetrics = calculateOdPlacementMetrics(placementTransitions);
  const dateTime = new Intl.DateTimeFormat("tr-TR", { dateStyle: "short", timeStyle: "medium", timeZone: "Europe/Istanbul" });
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email}>
    <AdminPageHeader eyebrow="Operasyon kuyruğu" title="Siparişler ve talepler" description="Ödeme sonrası hesap, davet ve veli bağlantısı otomatik ilerler. Burada yalnız istisnalar ve gerçek yerleştirme kararları görünür." icon={CreditCard} meta={`${lifecycle.exceptions.length} istisna · ${lifecycle.humanDecisions.length} yerleştirme`} />
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <PlacementMetric label="İlk iletişim" value={placementMetrics.firstContactHours === null ? "—" : `${placementMetrics.firstContactHours} sa`} detail={`${placementMetrics.firstContactSample} ölçüm · hedef ≤24 sa`} />
      <PlacementMetric label="Yerleştirme süresi" value={placementMetrics.placementHours === null ? "—" : `${placementMetrics.placementHours} sa`} detail={`${placementMetrics.placementSample} ölçüm · hedef ≤48 sa`} />
      <PlacementMetric label="Uygun slot bulunamadı" value={placementMetrics.noSlotRate === null ? "—" : `%${placementMetrics.noSlotRate}`} detail={`${placementMetrics.onboardingCount} onboarding · son 90 gün`} />
      <PlacementMetric label="Sonuçlar" value={`${placementMetrics.outcomes.assigned} grup`} detail={`${placementMetrics.outcomes.alternate} alternatif · ${placementMetrics.outcomes.waitlist} bekleme · ${placementMetrics.outcomes.refund} iade`} />
    </section>
    <OdLifecycleQueueSection queue={lifecycle} students={students} staff={staff} />
    <section id="cron-durumu" className="panel-surface mt-7 scroll-mt-24"><div className="flex flex-col gap-3 border-b border-[var(--site-line)] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-sm font-extrabold text-[var(--site-ink)]"><Activity size={17} /> Kritik cron heartbeat'leri</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Kalıcı son çalışma kanıtı · ODK yaşam döngüsü için sıkı 8 dakika eşiği</p></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-extrabold ${cronHealth.ok ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>{cronHealth.ok ? "Tümü sağlıklı" : `${cronHealth.jobs.filter((job) => job.status !== "healthy").length} alarm`}</span></div><div className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{cronHealth.jobs.map((job) => <article key={job.name} className={`rounded-2xl border p-4 ${job.name === "odk-exam-lifecycle" ? "border-[var(--brand-olive)]" : "border-[var(--site-line)]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold text-[var(--site-ink)]">{job.label}</p><p className="mt-1 font-mono text-[10px] text-[var(--site-muted)]">{job.name}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold uppercase ${job.status === "healthy" ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>{job.status === "healthy" ? "Sağlıklı" : job.status === "stale" ? "Gecikmiş" : job.status === "failed" ? "Başarısız" : "Kanıt yok"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-[10.5px]"><div><dt className="text-[var(--site-muted)]">Son başarı</dt><dd className="mt-1 font-bold text-[var(--site-ink)]">{job.lastSucceededAt ? dateTime.format(new Date(job.lastSucceededAt)) : "Henüz yok"}</dd></div><div><dt className="text-[var(--site-muted)]">Süre</dt><dd className="mt-1 font-bold text-[var(--site-ink)]">{job.lastDurationMs === null ? "—" : `${job.lastDurationMs} ms`}</dd></div><div><dt className="text-[var(--site-muted)]">İşlenen</dt><dd className="mt-1 font-bold text-[var(--site-ink)]">{job.processedCount}</dd></div><div><dt className="text-[var(--site-muted)]">Başarısız</dt><dd className="mt-1 font-bold text-[var(--site-ink)]">{job.failedCount}</dd></div></dl>{job.errorCode ? <p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 font-mono text-[10px] text-rose-800">{job.errorCode}</p> : null}</article>)}</div></section>
    <div className="mt-7 grid gap-6 xl:grid-cols-2"><section><h2 className="text-sm font-bold text-[var(--site-ink)]">Siparişler <span className="text-[var(--site-muted)]">({orders.length})</span></h2><div className="mt-3 space-y-2">{orders.map((order) => <div key={order.id} className="rounded-2xl border border-[var(--site-line)] bg-white p-4 shadow-[var(--panel-card-shadow)]"><div className="flex items-center justify-between gap-3"><div><Link href={`/panel/yonetim/siparisler/${order.id}`} className="text-sm font-bold text-[var(--site-ink)] underline-offset-2 hover:underline">{order.packageName}</Link><p className="mt-1 text-xs text-[var(--site-muted)]">{order.user?.fullName || order.user?.email || "Henüz hesaba bağlanmadı"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${order.status === "PAID" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{order.status} · {(order.totalCents / 100).toLocaleString("tr-TR")} ₺</span></div><OrderLinkForm orderId={order.id} students={students} currentUserId={order.userId} /></div>)}{!orders.length ? <p className="rounded-2xl border border-dashed border-[var(--site-line)] p-5 text-sm text-[var(--site-muted)]">Henüz sipariş yok.</p> : null}</div></section><section><h2 className="text-sm font-bold text-[var(--site-ink)]">Talepler <span className="text-[var(--site-muted)]">({leads.length})</span></h2><div className="mt-3 space-y-2">{leads.map((lead) => <div key={lead.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--site-line)] bg-white p-4 shadow-[var(--panel-card-shadow)]"><div className="min-w-0"><p className="truncate text-sm font-bold text-[var(--site-ink)]">{lead.fullName}</p><p className="mt-1 truncate text-xs text-[var(--site-muted)]">{lead.phone} · {lead.examType} · {lead.targetGoal}</p></div><LeadStatusControl id={lead.id} status={lead.intakeStatus} /></div>)}{!leads.length ? <p className="rounded-2xl border border-dashed border-[var(--site-line)] p-5 text-sm text-[var(--site-muted)]">Henüz talep yok.</p> : null}</div></section></div>
    <section id="eposta-kuyrugu" className="panel-surface mt-7 scroll-mt-24"><div className="flex items-center justify-between gap-3 border-b border-[var(--site-line)] p-5"><div><h2 className="flex items-center gap-2 text-sm font-extrabold text-[var(--site-ink)]"><MailWarning size={17} /> E-posta kuyruğu</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Bekleyen veya başarısız makbuz ve bildirimler</p></div><span className="rounded-full bg-[var(--site-bg-warm)] px-2.5 py-1 text-xs font-bold text-[var(--site-muted)]">{emailQueue.length}</span></div><div className="divide-y divide-[var(--site-line)]">{emailQueue.map((email) => <article key={email.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-bold text-[var(--site-ink)]">{email.subject}</h3><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold ${email.status === "PENDING" ? "bg-amber-50 text-amber-800" : email.status === "FAILED" ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-700"}`}>{email.status === "PENDING" ? "Bekliyor" : email.status === "FAILED" ? "Başarısız" : "Bırakıldı"}</span></div><p className="mt-1 text-xs text-[var(--site-muted)]">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(email.createdAt)} · {email.attempts} deneme</p></div>{email.status !== "PENDING" ? <EmailRetryButton id={email.id} /> : <span className="text-xs font-bold text-amber-700">Otomatik gönderilecek</span>}</article>)}{!emailQueue.length ? <p className="p-8 text-center text-sm text-[var(--site-muted)]">Bekleyen e-posta yok.</p> : null}</div></section>
  </PanelShell>;
}

function PlacementMetric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <article className="panel-metric-card"><p className="text-[10px] font-extrabold uppercase tracking-[.07em] text-[var(--site-muted)]">{label}</p><p className="mt-3 text-2xl font-black text-[var(--site-ink)]">{value}</p><p className="mt-1 text-[10.5px] text-[var(--site-muted)]">{detail}</p></article>;
}
