import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";
import { OrderLinkForm } from "@/components/panel/order-link-form";
import { AdminPageHeader } from "@/components/panel/admin-page-header";
import { CreditCard, MailWarning } from "lucide-react";
import { LeadStatusControl } from "@/components/panel/lead-status-control";
import { EmailRetryButton } from "@/components/panel/email-retry-button";

export const dynamic = "force-dynamic";

export default async function OperationsPage() {
  const session = await requireRole("ADMIN");
  const [orders, leads, studentsRaw, emailQueue] = await Promise.all([
    prisma.odOrder.findMany({ orderBy: { createdAt: "desc" }, take: 30, include: { user: { select: { fullName: true, email: true } } } }),
    prisma.leadSubmission.findMany({ orderBy: { submittedAt: "desc" }, take: 30 }),
    prisma.user.findMany({ where: { role: "STUDENT", status: "ACTIVE" }, orderBy: { fullName: "asc" }, select: { id: true, fullName: true, email: true } }),
    prisma.emailOutbox.findMany({ where: { status: { not: "SENT" } }, orderBy: { createdAt: "desc" }, take: 20, select: { id: true, subject: true, status: true, attempts: true, createdAt: true } }),
  ]);
  const students = studentsRaw.map((student) => ({ id: student.id, name: student.fullName || student.email }));
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}>
    <AdminPageHeader eyebrow="Operasyon kuyruğu" title="Siparişler ve talepler" description="Yeni başvuruları takip edin, siparişleri doğru öğrenci hesabına bağlayın ve veli paneline yansımasını kontrol edin." icon={CreditCard} meta={`${orders.length + leads.length} kayıt`} />
    <div className="mt-7 grid gap-6 xl:grid-cols-2"><section><h2 className="text-sm font-bold text-[var(--site-ink)]">Siparişler <span className="text-[var(--site-muted)]">({orders.length})</span></h2><div className="mt-3 space-y-2">{orders.map((order) => <div key={order.id} className="rounded-2xl border border-[var(--site-line)] bg-white p-4 shadow-[var(--panel-card-shadow)]"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold text-[var(--site-ink)]">{order.packageName}</p><p className="mt-1 text-xs text-[var(--site-muted)]">{order.user?.fullName || order.user?.email || "Henüz hesaba bağlanmadı"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${order.status === "PAID" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{order.status} · {(order.totalCents / 100).toLocaleString("tr-TR")} ₺</span></div><OrderLinkForm orderId={order.id} students={students} currentUserId={order.userId} /></div>)}{!orders.length ? <p className="rounded-2xl border border-dashed border-[var(--site-line)] p-5 text-sm text-[var(--site-muted)]">Henüz sipariş yok.</p> : null}</div></section><section><h2 className="text-sm font-bold text-[var(--site-ink)]">Talepler <span className="text-[var(--site-muted)]">({leads.length})</span></h2><div className="mt-3 space-y-2">{leads.map((lead) => <div key={lead.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--site-line)] bg-white p-4 shadow-[var(--panel-card-shadow)]"><div className="min-w-0"><p className="truncate text-sm font-bold text-[var(--site-ink)]">{lead.fullName}</p><p className="mt-1 truncate text-xs text-[var(--site-muted)]">{lead.phone} · {lead.examType} · {lead.targetGoal}</p></div><LeadStatusControl id={lead.id} status={lead.intakeStatus} /></div>)}{!leads.length ? <p className="rounded-2xl border border-dashed border-[var(--site-line)] p-5 text-sm text-[var(--site-muted)]">Henüz talep yok.</p> : null}</div></section></div>
    <section id="eposta-kuyrugu" className="panel-surface mt-7 scroll-mt-24"><div className="flex items-center justify-between gap-3 border-b border-[var(--site-line)] p-5"><div><h2 className="flex items-center gap-2 text-sm font-extrabold text-[var(--site-ink)]"><MailWarning size={17} /> E-posta kuyruğu</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Bekleyen veya başarısız makbuz ve bildirimler</p></div><span className="rounded-full bg-[var(--site-bg-warm)] px-2.5 py-1 text-xs font-bold text-[var(--site-muted)]">{emailQueue.length}</span></div><div className="divide-y divide-[var(--site-line)]">{emailQueue.map((email) => <article key={email.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-bold text-[var(--site-ink)]">{email.subject}</h3><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold ${email.status === "PENDING" ? "bg-amber-50 text-amber-800" : email.status === "FAILED" ? "bg-rose-50 text-rose-700" : "bg-slate-100 text-slate-700"}`}>{email.status === "PENDING" ? "Bekliyor" : email.status === "FAILED" ? "Başarısız" : "Bırakıldı"}</span></div><p className="mt-1 text-xs text-[var(--site-muted)]">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(email.createdAt)} · {email.attempts} deneme</p></div>{email.status !== "PENDING" ? <EmailRetryButton id={email.id} /> : <span className="text-xs font-bold text-amber-700">Otomatik gönderilecek</span>}</article>)}{!emailQueue.length ? <p className="p-8 text-center text-sm text-[var(--site-muted)]">Bekleyen e-posta yok.</p> : null}</div></section>
  </PanelShell>;
}
