import Link from "next/link";
import { CheckCircle2, CircleDashed, CreditCard, ExternalLink, Library, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";
import { PanelEmptyState } from "@/components/panel/empty-state";

export const dynamic = "force-dynamic";

export default async function ParentTrackingPage({ searchParams }: { searchParams: Promise<{ studentId?: string }> }) {
  const session = await requireRole("PARENT");
  const { studentId } = await searchParams;
  const links = await prisma.parentStudent.findMany({ where: { parentId: session.userId }, include: { student: { include: { user: { select: { id: true, fullName: true, email: true } } } } }, orderBy: { student: { user: { fullName: "asc" } } } });
  if (!links.length) return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}><PanelEmptyState title="Öğrenci bağlantınız hazırlanıyor." body="Bağlantı kurulduğunda ödev ve ödeme takibi burada görünür." /></PanelShell>;
  const selected = studentId ? links.find((item) => item.studentId === studentId) : links[0];
  if (!selected) notFound();
  const enrollments = await prisma.enrollment.findMany({ where: { studentId: selected.studentId, endedAt: null }, select: { groupId: true } });
  const [assignments, orders, materials] = await Promise.all([
    prisma.assignment.findMany({ where: { groupId: { in: enrollments.map((item) => item.groupId) }, isActive: true }, orderBy: { dueAt: "asc" }, include: { group: true, progress: { where: { studentId: selected.studentId }, take: 1 } } }),
    prisma.odOrder.findMany({ where: { userId: selected.student.user.id }, orderBy: { createdAt: "desc" }, take: 10, select: { id: true, packageName: true, status: true, totalCents: true, createdAt: true } }),
    prisma.learningMaterial.findMany({ where: { isActive: true, groupId: { in: enrollments.map((item) => item.groupId) } }, orderBy: { createdAt: "desc" }, take: 12, include: { group: { select: { name: true } } } }),
  ]);
  const name = selected.student.user.fullName || selected.student.user.email;
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}>
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.07em] text-[var(--brand-olive)]"><ShieldCheck size={15} /> Yalnızca bağlı öğrenciniz</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] text-[var(--site-ink)]">{name} · Ödev ve ödeme</h1></div>{links.length > 1 ? <nav className="flex gap-2" aria-label="Öğrenci seçimi">{links.map((link) => <Link key={link.studentId} href={`/panel/veli/takip?studentId=${link.studentId}`} className={`rounded-full px-3 py-2 text-xs font-bold ${link.studentId === selected.studentId ? "bg-[var(--brand-olive)] text-white" : "border border-[var(--site-line)] bg-white"}`}>{link.student.user.fullName || link.student.user.email}</Link>)}</nav> : null}</header>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="panel-surface p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Ödev ilerlemesi</h2><div className="mt-4 space-y-3">{assignments.map((assignment) => { const status = assignment.progress[0]?.status || "TODO"; const done = status === "DONE"; const overdue = !done && assignment.dueAt < new Date(); return <article key={assignment.id} className="rounded-2xl border border-[var(--site-line)] p-4"><div className="flex items-start gap-3">{done ? <CheckCircle2 size={19} className="mt-0.5 shrink-0 text-emerald-600" /> : <CircleDashed size={19} className={`mt-0.5 shrink-0 ${overdue ? "text-rose-600" : "text-amber-600"}`} />}<div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-[var(--site-ink)]">{assignment.title}</h3><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold ${done ? "bg-emerald-50 text-emerald-700" : overdue ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-800"}`}>{done ? "Tamamlandı" : overdue ? "Süresi geçti" : status === "IN_PROGRESS" ? "Yapılıyor" : "Bekliyor"}</span></div><p className="mt-1 text-xs text-[var(--site-muted)]">{assignment.group.name} · {new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(assignment.dueAt)}</p></div></div></article>; })}{!assignments.length ? <p className="text-sm text-[var(--site-muted)]">Aktif ödev bulunmuyor.</p> : null}</div></section><section className="panel-surface p-5"><h2 className="flex items-center gap-2 text-sm font-extrabold text-[var(--site-ink)]"><CreditCard size={17} /> Ödeme kayıtları</h2><div className="mt-4 space-y-3">{orders.map((order) => <article key={order.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--site-line)] p-4"><div><p className="text-xs font-bold text-[var(--site-ink)]">{order.packageName}</p><p className="mt-1 text-[10.5px] text-[var(--site-muted)]">{new Intl.DateTimeFormat("tr-TR").format(order.createdAt)}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${order.status === "PAID" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{order.status === "PAID" ? "Ödendi" : "Bekliyor"} · {(order.totalCents / 100).toLocaleString("tr-TR")} ₺</span></article>)}{!orders.length ? <p className="text-sm text-[var(--site-muted)]">Bağlı sipariş bulunmuyor.</p> : null}</div></section></div>
    <section className="panel-surface mt-5 p-5"><h2 className="flex items-center gap-2 text-sm font-extrabold text-[var(--site-ink)]"><Library size={17} /> Paylaşılan materyaller</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{materials.map((material) => <a key={material.id} href={material.blobPathname ? `/api/panel/materials/${material.id}/file` : material.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--site-line)] p-4 transition hover:bg-[var(--site-bg-warm)]"><span><strong className="block text-xs text-[var(--site-ink)]">{material.title}</strong><span className="mt-1 block text-[10.5px] text-[var(--site-muted)]">{material.group.name} · {material.kind}</span></span><ExternalLink size={14} className="text-[var(--brand-olive)]" /></a>)}{!materials.length ? <p className="text-sm text-[var(--site-muted)]">Henüz materyal paylaşılmadı.</p> : null}</div></section>
  </PanelShell>;
}
