import { expect, test } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { loginAs } from "./helpers/panel-login";
const db = new PrismaClient();
const run = crypto.randomUUID();
let studentId: string, studentUserId: string, parentUserId: string, assignmentId: string, sessionId: string;
const studentEmail = `ok-only-${run}@example.com`, parentEmail = `ok-parent-${run}@example.com`;
const password = process.env.PANEL_E2E_STUDENT_PASSWORD!;
const teacher = { email: process.env.PANEL_E2E_TEACHER_EMAIL!, password: process.env.PANEL_E2E_TEACHER_PASSWORD!, failureLabel: "coach" };
const student = { email: studentEmail, password, failureLabel: "ok-only" };
const parent = { email: parentEmail, password, failureLabel: "parent" };
const origin = { origin: "http://localhost:3000" };
test.describe.serial("Koçum görüşme ve yardım deneyimi", () => {
  test.beforeAll(async () => {
    const seed = await db.user.findUniqueOrThrow({ where: { id: "e2e-user-student" } });
    const created = await db.user.create({ data: { email: studentEmail, fullName: `Koçum Öğrencisi ${run}`, role: "STUDENT", passwordHash: seed.passwordHash, mustChangePassword: false, inviteAcceptedAt: new Date(), studentProfile: { create: {} }, productMemberships: { create: { product: "OK" } } }, include: { studentProfile: true } });
    studentUserId = created.id; studentId = created.studentProfile!.id;
    const createdParent = await db.user.create({ data: { email: parentEmail, role: "PARENT", passwordHash: seed.passwordHash, mustChangePassword: false, inviteAcceptedAt: new Date(), parentStudents: { create: { studentId } } } }); parentUserId = createdParent.id;
    const coach = await db.teacherProfile.findUniqueOrThrow({ where: { userId: "e2e-user-teacher" } });
    const assignment = await db.coachAssignment.create({ data: { studentId, coachId: coach.id } }); assignmentId = assignment.id;
  });
  test.afterAll(async () => { await db.weeklyPlan.deleteMany({ where: { studentId } }); await db.user.deleteMany({ where: { id: { in: [studentUserId, parentUserId] } } }); await db.$disconnect(); });
  test("koç linkli görüşme açar; veli saat ister; koç önerir ve öğrenci tek tıkla onaylar", async ({ page }) => {
    const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
    await loginAs(page, teacher);
    const createData = { studentId, scheduledAt: new Date(Date.now() + 23.9 * 3_600_000).toISOString(), meetingUrl: "https://example.com/ok-meeting", idempotencyKey: crypto.randomUUID() };
    const invalidCreate = await page.request.post("/api/panel/coaching-sessions", { data: { ...createData, unexpectedField: "invalid" }, headers: origin });
    expect(invalidCreate.status()).toBe(400);
    expect(await db.coachingSession.count({ where: { assignmentId } })).toBe(0);
    const created = await page.request.post("/api/panel/coaching-sessions", { data: createData, headers: origin }); expect(created.status(), await created.text()).toBe(201); sessionId = (await created.json()).id;
    const invalidMutation = await page.request.post(`/api/panel/coaching-sessions/${sessionId}`, { data: { action: "REQUEST", reason: "FREE_TEXT", expectedVersion: 1, idempotencyKey: crypto.randomUUID() }, headers: origin });
    expect(invalidMutation.status()).toBe(400);
    expect((await db.coachingSession.findUniqueOrThrow({ where: { id: sessionId } })).version).toBe(1);
    expect((await (await page.request.post("/api/panel/coaching-sessions", { data: createData, headers: origin })).json()).id).toBe(sessionId);
    await page.goto(`/panel/ogretmen/hazirlik/${studentId}`); await expect(page.getByRole("link", { name: "Görüşmeye katıl" })).toHaveAttribute("href", createData.meetingUrl);
    await loginAs(page, parent); await page.goto(`/panel/veli/kocluk?studentId=${studentId}`);
    await expect(page.getByRole("link", { name: "Görüşmeye katıl" })).toBeVisible();
    const requestResponse = page.waitForResponse((response) => response.url().endsWith(`/coaching-sessions/${sessionId}`) && response.request().method() === "POST");
    await page.getByRole("button", { name: "Saat değiştir", exact: true }).click(); expect((await requestResponse).status()).toBe(200);
    await expect(page.getByText(/Saat değişikliği talebiniz alındı/)).toBeVisible();
    await loginAs(page, teacher); await page.goto(`/panel/ogretmen/hazirlik/${studentId}`);
    const region = page.getByRole("region", { name: "Görüşme saati" });
    const proposed = new Date(Date.now() + 2 * 86_400_000);
    await region.getByLabel("Yeni saat önerisi").fill(new Date(proposed.getTime() + 3 * 3_600_000).toISOString().slice(0, 16));
    await region.getByLabel("Katılım bağlantısı").fill("https://example.com/ok-new-meeting");
    const proposalResponse = page.waitForResponse((response) => response.url().endsWith(`/coaching-sessions/${sessionId}`)); await region.getByRole("button", { name: "Yeni saati öner" }).click(); expect((await proposalResponse).status()).toBe(200);
    await loginAs(page, student); await page.goto("/panel/ogrenci/kocluk");
    const acceptResponse = page.waitForResponse((response) => response.url().endsWith(`/coaching-sessions/${sessionId}`)); await page.getByRole("button", { name: "Yeni saati onayla" }).click(); expect((await acceptResponse).status()).toBe(200);
    await expect(page.getByRole("link", { name: "Görüşmeye katıl" })).toHaveAttribute("href", "https://example.com/ok-new-meeting");
    const foreign = await page.request.post("/api/panel/coaching-sessions/e2e-foreign-session", { data: { action: "REQUEST", reason: "SCHOOL_SCHEDULE", expectedVersion: 1, idempotencyKey: crypto.randomUUID() }, headers: origin }); expect(foreign.status()).toBe(404);
    await loginAs(page, { email: process.env.PANEL_E2E_STUDENT_EMAIL!, password: process.env.PANEL_E2E_STUDENT_PASSWORD!, failureLabel: "foreign-student" });
    expect((await page.request.post(`/api/panel/coaching-sessions/${sessionId}`, { data: { action: "REQUEST", reason: "SCHOOL_SCHEDULE", expectedVersion: 4, idempotencyKey: crypto.randomUUID() }, headers: origin })).status()).toBe(404);
    await loginAs(page, { email: process.env.PANEL_E2E_PARENT_EMAIL!, password: process.env.PANEL_E2E_PARENT_PASSWORD!, failureLabel: "foreign-parent" });
    expect((await page.request.post(`/api/panel/coaching-sessions/${sessionId}`, { data: { action: "REQUEST", reason: "SCHOOL_SCHEDULE", expectedVersion: 4, idempotencyKey: crypto.randomUUID() }, headers: origin })).status()).toBe(404);
    expect(errors).toEqual([]);
  });
  test("görüşme kararları mevcut onaydan önce görünmez; yayın sonrası öğrenciye gelir", async ({ page }) => {
    await loginAs(page, teacher);
    const session = await db.coachingSession.findUniqueOrThrow({ where: { id: sessionId } });
    const completeData = { action: "COMPLETE", expectedVersion: session.version, idempotencyKey: crypto.randomUUID(), focus: "Bu haftanın odağı", sharedNote: "Ortak görüşme notu", privateNote: "PRIVATE_ONLY_COACH", decisions: [{ title: `Görüşme kararı ${run}`, scheduledFor: new Date().toISOString(), durationMinutes: 20 }] };
    const completed = await page.request.post(`/api/panel/coaching-sessions/${sessionId}`, { data: completeData, headers: origin }); expect(completed.status(), await completed.text()).toBe(200);
    expect((await page.request.post(`/api/panel/coaching-sessions/${sessionId}`, { data: completeData, headers: origin })).status()).toBe(200);
    const plan = await db.weeklyPlan.findFirstOrThrow({ where: { studentId }, include: { tasks: true } }); expect(plan.tasks).toHaveLength(1); expect(plan.status).toBe("DRAFT");
    await loginAs(page, student); await page.goto("/panel/ogrenci"); await expect(page.getByText(`Görüşme kararı ${run}`, { exact: false })).toHaveCount(0);
    await page.goto("/panel/ogrenci/kocluk"); await expect(page.getByText(`Görüşme kararı ${run}`, { exact: false })).toHaveCount(0); await expect(page.getByText("PRIVATE_ONLY_COACH", { exact: false })).toHaveCount(0);
    await page.goto("/panel/ogrenci/yon"); await expect(page.getByText(`Görüşme kararı ${run}`, { exact: false })).toHaveCount(0); await expect(page.getByText("PRIVATE_ONLY_COACH", { exact: false })).toHaveCount(0); await expect(page.getByText("Ortak görüşme notu").first()).toBeVisible();
    await loginAs(page, teacher); const approve = await page.request.post(`/api/panel/adaptive-plan/${plan.id}/approve`, { data: { expectedVersion: plan.version }, headers: origin }); expect(approve.status(), await approve.text()).toBe(200);
    await loginAs(page, student); await page.goto("/panel/ogrenci/plan"); await expect(page.getByText(`Görüşme kararı ${run}`).first()).toBeVisible();
    // Pazar günü planlama haftası bir sonraki haftadır; Yön Bugün yalnız içinde bulunulan haftayı gösterir.
    await page.goto("/panel/ogrenci/yon"); if (new Date().getDay() !== 0) await expect(page.getByText(`Görüşme kararı ${run}`).first()).toBeVisible(); await expect(page.getByText("PRIVATE_ONLY_COACH", { exact: false })).toHaveCount(0);
    await loginAs(page, parent); await page.goto(`/panel/veli/kocluk?studentId=${studentId}`); await expect(page.getByText("PRIVATE_ONLY_COACH", { exact: false })).toHaveCount(0); await expect(page.getByText(`Görüşme kararı ${run}`, { exact: false })).toHaveCount(0);
  });
  test("yalnız OK öğrencisinin özel check-in'i görünmez, yardımı atanmış koça gider", async ({ page }) => {
    await loginAs(page, student); await page.goto("/panel/ogrenci/check-in"); await expect(page.getByRole("heading", { name: "Nasıl ilerlediğini fark et, gerekirse yardım iste." })).toBeVisible();
    const input = { coachAssignmentId: assignmentId, energy: "LOW", confidence: "BUILDING", barrier: "NEED_EXAMPLE", shareWithTeacher: false, helpRequested: false };
    const privateResponse = await page.request.post("/api/panel/student-check-ins", { data: input, headers: origin }); expect(privateResponse.status(), await privateResponse.text()).toBe(201);
    await loginAs(page, teacher); await page.goto("/panel/ogretmen/yardim"); await expect(page.getByText(`Koçum Öğrencisi ${run}`, { exact: true })).toHaveCount(0);
    await loginAs(page, student);
    const foreign = await page.request.post("/api/panel/student-check-ins", { data: { ...input, coachAssignmentId: "foreign-coach-assignment" }, headers: origin }); expect(foreign.status()).toBe(404);
    const shared = await page.request.post("/api/panel/student-check-ins", { data: { ...input, shareWithTeacher: true, helpRequested: true }, headers: origin }); expect(shared.status(), await shared.text()).toBe(201); const help = (await shared.json()).checkIn.request;
    await loginAs(page, teacher); await page.goto("/panel/ogretmen/yardim"); await expect(page.getByRole("article").getByText(`Koçum Öğrencisi ${run}`, { exact: true })).toBeVisible();
    await db.coachAssignment.update({ where: { id: assignmentId }, data: { endedAt: new Date() } });
    expect((await page.request.post(`/api/panel/student-help-requests/${help.id}/respond`, { data: { expectedVersion: help.version, action: "EXTRA_EXAMPLE" }, headers: origin })).status()).toBe(404);
    await db.coachAssignment.update({ where: { id: assignmentId }, data: { endedAt: null } });
    const response = await page.request.post(`/api/panel/student-help-requests/${help.id}/respond`, { data: { expectedVersion: help.version, action: "EXTRA_EXAMPLE" }, headers: origin }); expect(response.status(), await response.text()).toBe(200);
    await loginAs(page, student); const feedback = await page.request.post(`/api/panel/student-help-requests/${help.id}/feedback`, { data: { expectedVersion: help.version + 1, helpful: true }, headers: origin }); expect(feedback.status(), await feedback.text()).toBe(200);
    await loginAs(page, parent); const forbidden = await page.request.post("/api/panel/student-check-ins", { data: input, headers: origin }); expect(forbidden.status()).toBe(403);
    await page.goto(`/panel/veli/kocluk?studentId=${studentId}`); await expect(page.getByText("NEED_EXAMPLE", { exact: false })).toHaveCount(0);
  });
});
