import Link from "next/link";
import { CalendarDays, ExternalLink, Video } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";

export const dynamic = "force-dynamic";
const dateTime = new Intl.DateTimeFormat("tr-TR", { timeZone: "Europe/Istanbul", weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" });

export default async function TeacherCalendarPage() {
  const session = await requireRole("TEACHER");
  const lessons = await prisma.lesson.findMany({ where: { teacherId: session.userId, startsAt: { gte: new Date(Date.now() - 14 * 86400000), lte: new Date(Date.now() + 60 * 86400000) } }, orderBy: { startsAt: "asc" }, include: { group: { select: { name: true, subject: true } }, attendances: true } });
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}><header><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[var(--brand-olive)]"><CalendarDays size={15} /> Ders programım</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] text-[var(--site-ink)]">Takviminiz, tek bakışta.</h1></header><div className="mt-7 space-y-3">{lessons.map((lesson) => <article key={lesson.id} className="flex flex-col gap-4 rounded-[22px] border border-[var(--site-line)] bg-white p-5 shadow-[var(--panel-card-shadow)] sm:flex-row sm:items-center"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${lesson.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : lesson.status === "CANCELLED" ? "bg-rose-50 text-rose-700" : "bg-[var(--brand-olive-soft)] text-[var(--brand-olive)]"}`}><Video size={20} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">{lesson.title}</h2><span className="rounded-full bg-[var(--site-bg-warm)] px-2 py-1 text-[9.5px] font-bold text-[var(--site-muted)]">{lesson.status === "PLANNED" ? "Planlı" : lesson.status === "COMPLETED" ? "Tamamlandı" : "İptal"}</span></div><p className="mt-1 text-xs text-[var(--site-muted)]">{lesson.group.name} · {lesson.group.subject} · {dateTime.format(lesson.startsAt)}</p></div><div className="flex gap-2">{lesson.meetingUrl && lesson.status === "PLANNED" ? <a href={lesson.meetingUrl} target="_blank" rel="noopener noreferrer" className="panel-quick-action panel-quick-action-primary"><ExternalLink size={14} /> Derse katıl</a> : null}<Link href={`/panel/ogretmen?lesson=${lesson.id}`} className="panel-quick-action">{lesson.status === "COMPLETED" ? "Notu aç" : "Ders ekranı"}</Link></div></article>)}{!lessons.length ? <p className="rounded-[24px] border border-dashed border-[var(--site-line)] p-10 text-center text-sm text-[var(--site-muted)]">Takvimde ders görünmüyor.</p> : null}</div></PanelShell>;
}
