import {
  LayoutDashboard,
  Inbox,
  Users,
  User,
  BookOpen,
  GraduationCap,
  ClipboardList,
  Package,
  Wallet,
  BarChart3,
  FileText,
  Settings,
  ShieldCheck,
  ScrollText,
  Search,
  Bell,
  Plus,
  ChevronRight,
  ChevronDown,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Check,
  X,
  Filter,
  ArrowUpDown,
  Calendar,
  Clock,
  Play,
  Download,
  Star,
  Folder,
  LayoutGrid,
  List,
  MoreHorizontal,
  Pin,
  Zap,
  Target,
  Flag,
  Sun,
  Moon,
  MessageSquare,
  Upload,
  CheckCircle2,
  AlertCircle,
  Eye,
  School,
  Users2,
  Megaphone,
  Home,
  Menu,
  Tag,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  home: Home,
  dashboard: LayoutDashboard,
  inbox: Inbox,
  users: Users,
  user: User,
  book: BookOpen,
  classroom: GraduationCap,
  assignment: ClipboardList,
  package: Package,
  money: Wallet,
  tag: Tag,
  chart: BarChart3,
  report: FileText,
  settings: Settings,
  shield: ShieldCheck,
  log: ScrollText,
  search: Search,
  bell: Bell,
  plus: Plus,
  chev: ChevronRight,
  chevd: ChevronDown,
  arrow: ArrowRight,
  up: ArrowUp,
  down: ArrowDown,
  check: Check,
  x: X,
  filter: Filter,
  sort: ArrowUpDown,
  cal: Calendar,
  clock: Clock,
  play: Play,
  dl: Download,
  star: Star,
  folder: Folder,
  grid: LayoutGrid,
  list: List,
  dots: MoreHorizontal,
  pin: Pin,
  bolt: Zap,
  target: Target,
  flag: Flag,
  sun: Sun,
  moon: Moon,
  msg: MessageSquare,
  upload: Upload,
  check2: CheckCircle2,
  alert: AlertCircle,
  eye: Eye,
  school: School,
  parent: Users2,
  megaphone: Megaphone,
  menu: Menu,
};

export type PanelIconName = keyof typeof ICONS;

type Props = {
  name: PanelIconName | string;
  size?: number;
  className?: string;
};

export function PanelIcon({ name, size = 16, className }: Props) {
  const Cmp = ICONS[name as string] ?? Folder;
  return <Cmp size={size} className={className} strokeWidth={1.6} />;
}
