import { AlertTriangle, BarChart3, CheckCircle2, ClipboardCheck, Download, UserRoundX, UsersRound, WalletCards } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";
import { AdminPageHeader } from "@/components/panel/admin-page-header";

export const dynamic = "force-dynamic";

export default async function AdminReportsPage() {
  const session = await requireRole("ADMIN"); const since = new Date(Date.now() - 30 * 86400000); const now = new Date();
  const [lessons, groups, attendance, overdueAssignments, pendingPayments] = await Promise.all([
    prisma.lesson.findMany({ where: { startsAt: { gte: since }, status: { not: "CANCELLED" } }, include: { teacher: { select: { id: true, fullName: true, email: true } } } }),
    prisma.group.findMany({ where: { isActive: true }, orderBy: { name: "asc" }, include: { enrollments: { where: { endedAt: null } }, assignments: { where: { isActive: true }, include: { progress: true } } } }),
    prisma.attendance.findMany({ where: { createdAt: { gte: since } }, select: { status: true } }),
    prisma.assignment.count({ where: { isActive: true, dueAt: { lt: now }, progress: { some: { status: { not: "DONE" } } } } }),
    prisma.odOrder.count({ where: { status: "PENDING" } }),
  ]);
  const finished = lessons.filter((item) => item.status === "COMPLETED").length; const present = attendance.filter((item) => item.status === "PRESENT" || item.status === "LATE").length; const noteRate = lessons.length ? Math.round((finished / lessons.length) * 100) : 0; const attendanceRate = attendance.length ? Math.round((present / attendance.length) * 100) : 0;
  const teachers = [...new Map(lessons.map((item) => [item.teacher.id, item.teacher])).values()].map((teacher) => { const rows = lessons.filter((item) => item.teacherId === teacher.id); return { name: teacher.fullName || teacher.email, total: rows.length, completed: rows.filter((item) => item.status === "COMPLETED").length }; }).sort((a,b) => b.total - a.total);
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}><AdminPageHeader eyebrow="Son 30 gün" title="Eğitimin nabzı, sayılarla." description="Not yazma düzenini, katılımı ve ödev tamamlanmasını sorun büyümeden görün." icon={BarChart3} meta={`${lessons.length} ders`} />
    <div className="mt-4 flex justify-end"><a href="/api/panel/reports/export?range=30" download className="panel-quick-action panel-quick-action-primary"><Download size={15} /> CSV raporu indir</a></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><article className="panel-metric-card"><CheckCircle2 size={18} className="text-emerald-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">%{noteRate}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Ders tamamlama</p></article><article className="panel-metric-card"><UsersRound size={18} className="text-sky-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">%{attendanceRate}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Katılım</p></article><article className="panel-metric-card"><ClipboardCheck size={18} className="text-violet-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{groups.reduce((sum, group) => sum + group.assignments.length, 0)}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Aktif ödev</p></article><article className="panel-metric-card"><AlertTriangle size={18} className="text-rose-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{overdueAssignments}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Gecikmiş çalışma</p></article><article className="panel-metric-card"><UserRoundX size={18} className="text-orange-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{groups.filter((group) => !group.enrollments.length).length}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Boş grup</p></article><article className="panel-metric-card"><WalletCards size={18} className="text-amber-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{pendingPayments}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Bekleyen ödeme</p></article></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="panel-surface overflow-hidden"><div className="border-b border-[var(--site-line)] p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Öğretmen ders tamamlama</h2></div><div className="divide-y divide-[var(--site-line)]">{teachers.map((teacher) => { const percent = teacher.total ? Math.round((teacher.completed / teacher.total) * 100) : 0; return <article key={teacher.name} className="p-5"><div className="flex justify-between text-xs font-bold"><span>{teacher.name}</span><span>{teacher.completed}/{teacher.total} · %{percent}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--site-bg-warm)]"><div className="h-full rounded-full bg-[var(--brand-olive)]" style={{ width: `${percent}%` }} /></div></article>; })}</div></section><section className="panel-surface overflow-hidden"><div className="border-b border-[var(--site-line)] p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Grup ödev ilerlemesi</h2></div><div className="divide-y divide-[var(--site-line)]">{groups.map((group) => { const rows = group.assignments.flatMap((item) => item.progress); const done = rows.filter((item) => item.status === "DONE").length; const percent = rows.length ? Math.round((done / rows.length) * 100) : 0; return <article key={group.id} className="p-5"><div className="flex justify-between text-xs font-bold"><span>{group.name}</span><span>{group.enrollments.length} öğrenci · %{percent}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--site-bg-warm)]"><div className="h-full rounded-full bg-violet-600" style={{ width: `${percent}%` }} /></div></article>; })}</div></section></div>
  </PanelShell>;
}
