import { Activity, AlertTriangle, BarChart3, Bot, CheckCircle2, ClipboardCheck, Download, ListChecks, RotateCcw, UserRoundX, UsersRound, WalletCards } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { AdminPageHeader } from "@/components/panel/admin-page-header";
import { calculatePanelSloReport } from "@/lib/panel-slo";
import { getPanelFeatureFlags } from "@/lib/panel-feature-flags";

export const dynamic = "force-dynamic";

function formatSloValue(value: number | null, unit: "ms" | "percent") {
  if (value === null) return "—";
  if (unit === "percent") return `%${value.toLocaleString("tr-TR", { maximumFractionDigits: 2 })}`;
  if (value >= 60_000) return `${(value / 60_000).toLocaleString("tr-TR", { maximumFractionDigits: 1 })} dk`;
  return `${(value / 1000).toLocaleString("tr-TR", { maximumFractionDigits: 1 })} sn`;
}

export default async function AdminReportsPage() {
  const session = await requireRole("ADMIN"); const since = new Date(Date.now() - 30 * 86400000); const now = new Date(); const featureFlags = getPanelFeatureFlags();
  const [lessons, groups, attendance, overdueAssignments, pendingPayments, productEvents, reviewItems, aiDrafts] = await Promise.all([
    prisma.lesson.findMany({ where: { startsAt: { gte: since }, status: { not: "CANCELLED" } }, include: { teacher: { select: { id: true, fullName: true, email: true } } } }),
    prisma.group.findMany({ where: { isActive: true }, orderBy: { name: "asc" }, include: { enrollments: { where: { endedAt: null } }, assignments: { where: { isActive: true }, include: { progress: true } } } }),
    prisma.attendance.findMany({ where: { createdAt: { gte: since } }, select: { status: true } }),
    prisma.assignment.count({ where: { isActive: true, dueAt: { lt: now }, progress: { some: { status: { not: "DONE" } } } } }),
    prisma.odOrder.count({ where: { status: "PENDING" } }),
    prisma.productEvent.findMany({ where: { occurredAt: { gte: since } }, select: { name: true, properties: true, occurredAt: true } }),
    featureFlags.reviewQueue ? prisma.reviewItem.findMany({ where: { createdAt: { gte: since } }, select: { createdAt: true, attempts: { select: { reviewedAt: true, response: true, stageBefore: true } } } }) : Promise.resolve([]),
    featureFlags.teacherAiDrafts ? prisma.teacherAiDraft.findMany({ where: { createdAt: { gte: since } }, select: { status: true, provider: true, estimatedCostMicrousd: true } }) : Promise.resolve([]),
  ]);
  const finished = lessons.filter((item) => item.status === "COMPLETED").length; const present = attendance.filter((item) => item.status === "PRESENT" || item.status === "LATE").length; const noteRate = lessons.length ? Math.round((finished / lessons.length) * 100) : 0; const attendanceRate = attendance.length ? Math.round((present / attendance.length) * 100) : 0;
  const teachers = [...new Map(lessons.map((item) => [item.teacher.id, item.teacher])).values()].map((teacher) => { const rows = lessons.filter((item) => item.teacherId === teacher.id); return { name: teacher.fullName || teacher.email, total: rows.length, completed: rows.filter((item) => item.status === "COMPLETED").length }; }).sort((a,b) => b.total - a.total);
  const sloMetrics = calculatePanelSloReport(productEvents);
  const sevenDayEligible = reviewItems.filter((item) => item.createdAt <= new Date(now.getTime() - 7 * 86400000)); const sevenDayResolved = sevenDayEligible.filter((item) => item.attempts.some((attempt) => attempt.reviewedAt <= new Date(item.createdAt.getTime() + 7 * 86400000))).length; const sevenDayRate = sevenDayEligible.length ? Math.round((sevenDayResolved / sevenDayEligible.length) * 100) : null;
  const retentionAttempts = reviewItems.flatMap((item) => item.attempts).filter((attempt) => attempt.stageBefore === 4); const retentionCorrect = retentionAttempts.filter((attempt) => attempt.response === "CORRECT").length; const retentionRate = retentionAttempts.length ? Math.round((retentionCorrect / retentionAttempts.length) * 100) : null;
  const generatedPlanTaskCount = productEvents.filter((event) => event.name === "plan_generated").reduce((sum, event) => { const value = event.properties as { taskCount?: unknown }; return sum + (typeof value.taskCount === "number" ? value.taskCount : 0); }, 0); const completedPlanTaskCount = productEvents.filter((event) => event.name === "plan_task_completed").length; const planCompletionRate = generatedPlanTaskCount ? Math.min(100, Math.round((completedPlanTaskCount / generatedPlanTaskCount) * 100)) : null;
  const aiReviewed = aiDrafts.filter((item) => item.status !== "DRAFT"); const aiApproved = aiDrafts.filter((item) => item.status === "APPROVED").length; const aiApprovalRate = aiReviewed.length >= 5 ? Math.round((aiApproved / aiReviewed.length) * 100) : null; const aiFallbackRate = aiDrafts.length >= 5 ? Math.round((aiDrafts.filter((item) => item.provider !== "OPENAI").length / aiDrafts.length) * 100) : null; const aiFlagRate = aiReviewed.length >= 5 ? Math.round((aiDrafts.filter((item) => item.status === "FLAGGED").length / aiReviewed.length) * 100) : null; const aiKnownCostMicrousd = aiDrafts.reduce((sum, item) => sum + (item.estimatedCostMicrousd || 0), 0); const aiUnknownCost = aiDrafts.some((item) => item.provider === "OPENAI" && item.estimatedCostMicrousd === null);
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email}><AdminPageHeader eyebrow="Son 30 gün" title="Eğitimin nabzı, sayılarla." description="Not yazma düzenini, katılımı ve ödev tamamlanmasını sorun büyümeden görün." icon={BarChart3} meta={`${lessons.length} ders`} />
    <div className="mt-4 flex justify-end"><a href="/api/panel/reports/export?range=30" download className="panel-quick-action panel-quick-action-primary"><Download size={15} /> CSV raporu indir</a></div>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><article className="panel-metric-card"><CheckCircle2 size={18} className="text-emerald-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">%{noteRate}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Ders tamamlama</p></article><article className="panel-metric-card"><UsersRound size={18} className="text-dc-ink-muted" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">%{attendanceRate}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Katılım</p></article><article className="panel-metric-card"><ClipboardCheck size={18} className="text-dc-brand-strong" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{groups.reduce((sum, group) => sum + group.assignments.length, 0)}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Aktif ödev</p></article><article className="panel-metric-card"><AlertTriangle size={18} className="text-rose-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{overdueAssignments}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Gecikmiş çalışma</p></article><article className="panel-metric-card"><UserRoundX size={18} className="text-[#A5764A]" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{groups.filter((group) => !group.enrollments.length).length}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Boş grup</p></article><article className="panel-metric-card"><WalletCards size={18} className="text-amber-700" /><p className="mt-4 text-3xl font-extrabold text-[var(--site-ink)]">{pendingPayments}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Bekleyen ödeme</p></article></section>
    {featureFlags.reviewQueue ? <section className="mt-5 grid gap-3 sm:grid-cols-2"><article className="panel-metric-card"><RotateCcw size={18} className="text-[var(--brand-olive)]" /><p className="mt-4 text-3xl font-extrabold">{sevenDayRate === null ? "—" : `%${sevenDayRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">7 günde yeniden çözüm · {sevenDayEligible.length} uygun öğe · hedef ≥%60</p></article><article className="panel-metric-card"><CheckCircle2 size={18} className="text-emerald-700" /><p className="mt-4 text-3xl font-extrabold">{retentionRate === null ? "—" : `%${retentionRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">30 günlük doğru geri çağırma · {retentionAttempts.length} deneme</p></article></section> : null}
    {featureFlags.adaptivePlan ? <section className="mt-5"><article className="panel-metric-card"><ListChecks size={18} className="text-dc-brand-strong" /><p className="mt-4 text-3xl font-extrabold">{planCompletionRate === null ? "—" : `%${planCompletionRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Haftalık plan görevi tamamlama · {completedPlanTaskCount}/{generatedPlanTaskCount} · pilot baz çizgisi</p></article></section> : null}
    {featureFlags.teacherAiDrafts ? <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="panel-metric-card"><Bot size={18} className="text-dc-brand-strong" /><p className="mt-4 text-3xl font-extrabold">{aiApprovalRate === null ? "—" : `%${aiApprovalRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">AI taslak onayı · {aiReviewed.length} inceleme · en az 5 örnek</p></article><article className="panel-metric-card"><Activity size={18} className="text-amber-700" /><p className="mt-4 text-3xl font-extrabold">{aiFallbackRate === null ? "—" : `%${aiFallbackRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Güvenli fallback · {aiDrafts.length} üretim</p></article><article className="panel-metric-card"><AlertTriangle size={18} className="text-rose-700" /><p className="mt-4 text-3xl font-extrabold">{aiFlagRate === null ? "—" : `%${aiFlagRate}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Doğrulanmış hata işareti · küçük örnek gizlenir</p></article><article className="panel-metric-card"><WalletCards size={18} className="text-dc-ink-muted" /><p className="mt-4 text-3xl font-extrabold">{aiUnknownCost ? "Eksik" : `$${(aiKnownCostMicrousd / 1_000_000).toLocaleString("tr-TR", { maximumFractionDigits: 4 })}`}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Bilinen model maliyeti · fiyat env'i yoksa rollout durur</p></article></section> : null}
    <section className="mt-5 panel-surface p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#eef2df] text-[var(--brand-olive)]"><Activity size={19} /></span><div><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Kritik yolculuk SLO'ları</h2><p className="mt-1 text-xs leading-5 text-[var(--site-muted)]">Son 30 gün · Kimliksiz ürün event'leri · En az 5 örnek olmadan durum kararı verilmez.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{sloMetrics.map((metric) => <article key={metric.key} className="rounded-2xl border border-[var(--site-line)] bg-[var(--site-bg-warm)] p-4"><div className={`inline-flex rounded-full px-2 py-1 text-[10px] font-extrabold uppercase tracking-[.06em] ${metric.status === "healthy" ? "bg-emerald-100 text-emerald-800" : metric.status === "breached" ? "bg-rose-100 text-rose-800" : "bg-slate-100 text-slate-600"}`}>{metric.status === "healthy" ? "Hedefte" : metric.status === "breached" ? "Hedef dışı" : "Veri bekleniyor"}</div><p className="mt-4 text-2xl font-extrabold tracking-[-.04em] text-[var(--site-ink)]">{formatSloValue(metric.value, metric.unit)}</p><p className="mt-1 text-xs font-bold text-[var(--site-body)]">{metric.label}</p><p className="mt-2 text-[11px] text-[var(--site-muted)]">{metric.sampleSize} örnek · hedef {metric.comparison === "gte" ? "≥" : "≤"}{formatSloValue(metric.target, metric.unit)}</p></article>)}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="panel-surface overflow-hidden"><div className="border-b border-[var(--site-line)] p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Öğretmen ders tamamlama</h2></div><div className="divide-y divide-[var(--site-line)]">{teachers.map((teacher) => { const percent = teacher.total ? Math.round((teacher.completed / teacher.total) * 100) : 0; return <article key={teacher.name} className="p-5"><div className="flex justify-between text-xs font-bold"><span>{teacher.name}</span><span>{teacher.completed}/{teacher.total} · %{percent}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-dc-line-soft" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} aria-label={`${teacher.name} ders tamamlama oranı`}><div className="h-full rounded-full bg-dc-brand" style={{ width: `${percent}%` }} /></div></article>; })}</div></section><section className="panel-surface overflow-hidden"><div className="border-b border-[var(--site-line)] p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Grup ödev ilerlemesi</h2></div><div className="divide-y divide-[var(--site-line)]">{groups.map((group) => { const rows = group.assignments.flatMap((item) => item.progress); const done = rows.filter((item) => item.status === "DONE").length; const percent = rows.length ? Math.round((done / rows.length) * 100) : 0; return <article key={group.id} className="p-5"><div className="flex justify-between text-xs font-bold"><span>{group.name}</span><span>{group.enrollments.length} öğrenci · %{percent}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-dc-line-soft" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} aria-label={`${group.name} ödev ilerlemesi`}><div className="h-full rounded-full bg-dc-brand" style={{ width: `${percent}%` }} /></div></article>; })}</div></section></div>
  </PanelShell>;
}
