/** Public marketing aliases. Exact paths leave package checkout children intact. */
export const publicLegacyRedirects = [
  { source: "/matematik-ders-paketi", destination: "/paketler", permanent: true },
  { source: "/paket", destination: "/paketler", permanent: true },
  { source: "/ders-paketleri", destination: "/paketler", permanent: true },
  { source: "/lgs", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/yks", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/matematik", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/tyt", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/ayt", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/online-dershane", destination: "/urunler/online-dershanem", permanent: true },
  { source: "/deneme-kulubu", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/odk", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/odk-paketleri", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/online-deneme-kulubu", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/deneme-paketleri", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/tyt-deneme-kulubu", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/lgs-deneme-kulubu", destination: "/urunler/online-deneme-kulubum", permanent: true },
  { source: "/misyonumuz", destination: "/hakkimizda", permanent: true },
  { source: "/kamplar", destination: "/urunler", permanent: true },
];
