import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CheckCircle2, FileText, Target, XCircle } from "lucide-react";
import { requireProductRole } from "@/lib/auth/guards";
import { getReleasedStudentResult } from "@/lib/odk/student-exam-server";
import { PanelShell } from "@/components/panel/panel-shell";
import { OdkPanelNav } from "@/components/odk/odk-panel-nav";

export const dynamic = "force-dynamic";

export default async function OdkStudentResultPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireProductRole("ODK", "STUDENT"); const { id } = await params;
  const data = await getReleasedStudentResult(id, session.userId); if (!data) notFound();
  const { exam, score, answerKeyAvailable } = data;
  const weak = score.outcomeScores.filter((item) => Number(item.accuracyRate) < 50);
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} product="ODK" nav={<OdkPanelNav role={session.role} />}>
    <Link href={`/panel/odk/ogrenci/denemeler/${id}`} className="inline-flex items-center gap-2 text-sm font-bold text-[var(--site-body)]"><ArrowLeft size={15} /> Denemeye dön</Link>
    <header className="mt-6"><p className="text-xs font-extrabold uppercase tracking-[.1em] text-[var(--brand-olive)]">{exam.family} matematik sonucu</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[var(--site-ink)]">{exam.title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[var(--site-body)]">Sonucun yalnız kendi cevapların ve denemenin kilitli cevap anahtarı kullanılarak hesaplandı.</p></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Net", Number(score.totalNet).toFixed(2), Target, "text-[var(--brand-olive)]"], ["Doğru", score.correctCount, CheckCircle2, "text-emerald-600"], ["Yanlış", score.wrongCount, XCircle, "text-rose-600"], ["Boş", score.blankCount, FileText, "text-slate-500"]].map(([label, value, Icon, color]) => { const MetricIcon = Icon as typeof Target; return <article key={String(label)} className="panel-metric-card"><MetricIcon size={18} className={String(color)} /><p className="mt-4 text-2xl font-black text-[var(--site-ink)]">{String(value)}</p><p className="mt-1 text-xs text-[var(--site-muted)]">{String(label)}</p></article>; })}</section>
    <section className="mt-6 grid gap-6 xl:grid-cols-2"><div className="panel-surface p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-extrabold text-[var(--site-ink)]">Kazanım görünümü</h2><span className="text-xs font-bold text-[var(--site-muted)]">{weak.length} gelişim alanı</span></div><div className="mt-4 space-y-3">{score.outcomeScores.map((item) => { const accuracy = Number(item.accuracyRate); return <article key={item.outcome.code} className="rounded-2xl border border-[var(--site-line)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-[var(--brand-olive)]">{item.outcome.code}</p><h3 className="mt-1 text-sm font-bold text-[var(--site-ink)]">{item.outcome.title}</h3><p className="mt-1 text-xs text-[var(--site-muted)]">{item.outcome.unit.name} · {item.correctCount} doğru, {item.wrongCount} yanlış, {item.blankCount} boş</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${accuracy >= 75 ? "bg-emerald-50 text-emerald-700" : accuracy >= 50 ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}>%{accuracy.toFixed(0)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${accuracy >= 75 ? "bg-emerald-500" : accuracy >= 50 ? "bg-amber-500" : "bg-rose-500"}`} style={{ width: `${accuracy}%` }} /></div></article>; })}</div></div>
    <div className="panel-surface p-5"><h2 className="font-extrabold text-[var(--site-ink)]">Soru cevap dökümü</h2><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{score.questionResults.map((item) => <div key={item.question.questionNumber} className={`rounded-xl p-3 text-xs font-bold ${item.result === "CORRECT" ? "bg-emerald-50 text-emerald-800" : item.result === "WRONG" ? "bg-rose-50 text-rose-800" : "bg-slate-100 text-slate-700"}`}><p>Soru {item.question.questionNumber}</p><p className="mt-1">Sen: {item.selectedOption || "—"} · Doğru: {item.correctOption}</p></div>)}</div>{answerKeyAvailable && exam.currentVersion?.files.length ? <a href={`/api/odk/student/exams/${id}/answer-key`} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[var(--site-ink)] px-4 py-2.5 text-sm font-bold text-white"><FileText size={15} /> Cevap anahtarı PDF</a> : null}</div></section>
  </PanelShell>;
}
