import Link from "next/link";
import { notFound } from "next/navigation";
import { HeartHandshake } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { getPanelFeatureFlags } from "@/lib/panel-feature-flags";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelEmptyState } from "@/components/panel/empty-state";
import { CalmDigestCard } from "@/components/panel/calm-digest-card";
import { recordPanelProductEvent } from "@/lib/panel-product-events";

export const dynamic = "force-dynamic";
export default async function ParentWeeklyDigestPage({ searchParams }: { searchParams: Promise<{ studentId?: string }> }) { const session = await requireRole("PARENT"); if (!getPanelFeatureFlags().parentWeeklyDigest) notFound(); const params = await searchParams; const links = await prisma.parentStudent.findMany({ where: { parentId: session.userId }, include: { student: { include: { user: { select: { fullName: true, email: true } } } } }, orderBy: { student: { user: { fullName: "asc" } } } }); const selected = params.studentId ? links.find((link) => link.studentId === params.studentId) : links[0]; if (!selected) notFound(); const digest = await prisma.weeklyDigest.findFirst({ where: { studentId: selected.studentId, status: "PUBLISHED" }, orderBy: { weekStart: "desc" }, include: { feedback: { where: { userId: session.userId }, take: 1 } } }); if (!digest) return <PanelShell role={session.role} fullName={session.fullName} email={session.email}><PanelEmptyState title="Haftalık özet henüz yayınlanmadı." body="Öğretmen önizlemeyi tamamladığında öğrenciyle aynı anda burada açılır." /></PanelShell>; const ageDays = digest.publishedAt ? (Date.now() - digest.publishedAt.getTime()) / 86400000 : 0; await recordPanelProductEvent({ name: "weekly_digest_viewed", properties: { actorRole: "PARENT", trendBand: digest.trendBand as "IMPROVING" | "STEADY" | "BUILDING" | "LIMITED_DATA", ageBand: ageDays <= 2 ? "0-2D" : ageDays <= 7 ? "3-7D" : "8D+" } }, session.role); const feedback = digest.feedback[0]; const name = selected.student.user.fullName || selected.student.user.email; return <PanelShell role={session.role} fullName={session.fullName} email={session.email}><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[var(--brand-olive)]"><HeartHandshake size={15} /> Haftada bir sakin bakış</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{name}</h1></div>{links.length > 1 ? <nav className="flex gap-2">{links.map((link) => <Link key={link.studentId} href={`/panel/veli/haftalik?studentId=${link.studentId}`} className="panel-quick-action">{link.student.user.fullName || link.student.user.email}</Link>)}</nav> : null}</header><div className="mt-7"><CalmDigestCard viewerRole="PARENT" digest={{ id: digest.id, goodThingOne: digest.goodThingOne, goodThingTwo: digest.goodThingTwo, supportArea: digest.supportArea, homeQuestion: digest.homeQuestion, dataThrough: digest.dataThrough.toISOString(), trendBand: digest.trendBand, feedback: feedback ? { helpful: feedback.helpful, anxietyPulse: feedback.anxietyPulse } : null }} /></div></PanelShell>; }
