import { ExternalLink, FileText, Library, Link2, Video } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";
import { PanelNav } from "@/components/panel/panel-nav";

export const dynamic = "force-dynamic";

export default async function StudentMaterialsPage() { const session = await requireRole("STUDENT"); const profile = await prisma.studentProfile.findUnique({ where: { userId: session.userId }, select: { id: true } }); const materials = profile ? await prisma.learningMaterial.findMany({ where: { isActive: true, group: { enrollments: { some: { studentId: profile.id, endedAt: null } } } }, orderBy: { createdAt: "desc" }, include: { group: { select: { name: true, subject: true } } } }) : []; const icons = { LINK: Link2, PDF: FileText, VIDEO: Video }; return <PanelShell role={session.role} fullName={session.fullName} email={session.email} nav={<PanelNav role={session.role} />}><header><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[var(--brand-olive)]"><Library size={15} /> Kaynaklarım</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em] text-[var(--site-ink)]">İhtiyacın olan her şey burada.</h1></header><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{materials.map((material) => { const Icon = icons[material.kind]; const href = material.blobPathname ? `/api/panel/materials/${material.id}/file` : material.url; return <article key={material.id} className="rounded-[24px] border border-[var(--site-line)] bg-white p-5 shadow-[var(--panel-card-shadow)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--brand-olive-soft)] text-[var(--brand-olive)]"><Icon size={19} /></span><p className="mt-4 text-[10px] font-bold uppercase text-[var(--site-muted)]">{material.group.name} · {material.group.subject}</p><h2 className="mt-2 text-base font-extrabold text-[var(--site-ink)]">{material.title}</h2><p className="mt-2 min-h-10 text-xs leading-5 text-[var(--site-body)]">{material.description || "Öğretmeninin paylaştığı çalışma kaynağı."}</p><a href={href} target="_blank" rel="noreferrer" className="panel-quick-action panel-quick-action-primary mt-5 w-full justify-center">Kaynağı aç <ExternalLink size={14} /></a></article>; })}{!materials.length ? <p className="rounded-[24px] border border-dashed border-[var(--site-line)] p-10 text-center text-sm text-[var(--site-muted)] md:col-span-2 xl:col-span-3">Henüz paylaşılmış materyal yok.</p> : null}</div></PanelShell>; }
