"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export function AdminAccessibilityAccommodationForm({ userId, initial }: { userId: string; initial: { version: number; assessmentExtraPercent: number; breaksAllowed: boolean } }) {
  const router = useRouter(); const [version, setVersion] = useState(initial.version); const [extra, setExtra] = useState(initial.assessmentExtraPercent); const [breaks, setBreaks] = useState(initial.breaksAllowed); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save() { setBusy(true); setMessage(""); const response = await fetch(`/api/panel/users/${userId}/accessibility`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: version, assessmentExtraPercent: extra, breaksAllowed: breaks }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) return setMessage(data.error || "Düzenleme kaydedilemedi."); setVersion(data.version); setMessage("İşlevsel akademik düzenleme kaydedildi."); router.refresh(); }
  return <section className="panel-surface mt-5 p-5"><h2 className="text-sm font-extrabold">Akademik makul düzenleme</h2><p className="mt-2 text-xs leading-5 text-[var(--site-body)]">Tanı veya belge metni girmeyin. Yalnız öğretmenin uygulaması gereken işlevsel düzenlemeyi seçin.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="panel-label">Değerlendirme ek süresi<select aria-label="Değerlendirme ek süresi" value={extra} onChange={(event) => setExtra(Number(event.target.value))} className="panel-input mt-2"><option value={0}>Ek süre yok</option><option value={25}>%25 ek süre</option><option value={50}>%50 ek süre</option><option value={100}>%100 ek süre</option></select></label><label className="flex items-center gap-3 rounded-2xl border border-[var(--site-line)] p-4 text-sm font-bold"><input type="checkbox" checked={breaks} onChange={(event) => setBreaks(event.target.checked)} /> Planlı kısa molaya izin ver</label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p role="status" className="text-xs font-bold text-[var(--brand-olive)]">{message}</p><button type="button" disabled={busy} onClick={save} className="panel-quick-action panel-quick-action-primary">{busy ? "Kaydediliyor…" : "Düzenlemeyi kaydet"}</button></div></section>;
}
