"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { CurriculumExam, MockExamErrorCategory, UserRole } from "@prisma/client";
import { CheckCircle2, ClipboardPaste, RotateCcw, Save, TimerReset } from "lucide-react";
import { mockExamErrorLabels, mockExamTemplates, sectionNet, summarizeMockExamTrend } from "@/lib/mock-exams";
import { sendPanelEvent } from "@/lib/panel-event-client";

type SectionState = { subjectCode: string; correctCount: number; incorrectCount: number; blankCount: number; durationMinutes: number; errorCategories: MockExamErrorCategory[] };
export type MockExamView = { id: string; studentId: string; exam: CurriculumExam; title: string; publisher: string; takenAt: string; durationMinutes: number | null; nextAction: string; sections: { id: string; subjectCode: string; subjectName: string; questionCount: number; correctCount: number; incorrectCount: number; blankCount: number; durationMinutes: number | null; errors: MockExamErrorCategory[] }[] };

function initialSections(exam: CurriculumExam): SectionState[] { return mockExamTemplates[exam].sections.map((section) => ({ subjectCode: section.code, correctCount: 0, incorrectCount: 0, blankCount: section.questions, durationMinutes: 0, errorCategories: [] })); }
function countBand(count: number) { return count === 0 ? "0" as const : count === 1 ? "1" as const : count <= 3 ? "2-3" as const : "4+" as const; }

export function MockExamWorkspace({ role, students, initialExams, canCreate = true, canReview = false }: { role: UserRole; students: { id: string; name: string }[]; initialExams: MockExamView[]; canCreate?: boolean; canReview?: boolean }) {
  const [examType, setExamType] = useState<CurriculumExam>("LGS");
  const [studentId, setStudentId] = useState(students[0]?.id || "");
  const [sections, setSections] = useState<SectionState[]>(initialSections("LGS"));
  const [previous, setPrevious] = useState<SectionState[] | null>(null);
  const [title, setTitle] = useState(""); const [publisher, setPublisher] = useState("");
  const [takenAt, setTakenAt] = useState(new Date().toISOString().slice(0, 10));
  const [durationMinutes, setDurationMinutes] = useState(mockExamTemplates.LGS.defaultDuration);
  const [paste, setPaste] = useState(""); const [status, setStatus] = useState(""); const [saving, setSaving] = useState(false);
  const [pasteApplied, setPasteApplied] = useState(false);
  const [exams, setExams] = useState(initialExams);
  const startedAt = useRef<number | null>(null);
  const started = useRef(false);
  const visibleExams = studentId && role !== "STUDENT" ? exams.filter((exam) => exam.studentId === studentId) : exams;
  const trend = useMemo(() => summarizeMockExamTrend(visibleExams.map((exam) => ({ exam: exam.exam, takenAt: new Date(exam.takenAt), sections: exam.sections.map((section) => ({ ...section, errors: section.errors.map((category) => ({ category })) })) }))), [visibleExams]);

  useEffect(() => { sendPanelEvent({ name: "mock_heatmap_viewed", properties: { examType: visibleExams.length && visibleExams.every((item) => item.exam === visibleExams[0].exam) ? visibleExams[0].exam : "MIXED", examCountBand: countBand(visibleExams.length) } }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function markStarted() { if (started.current) return; started.current = true; startedAt.current = Date.now(); if (role !== "PARENT") sendPanelEvent({ name: "mock_exam_entry_started", properties: { examType, actorRole: role as "ADMIN" | "TEACHER" | "STUDENT" } }); }
  function changeExam(next: CurriculumExam) { markStarted(); setExamType(next); setSections(initialSections(next)); setPrevious(null); setDurationMinutes(mockExamTemplates[next].defaultDuration); }
  function updateSection(index: number, patch: Partial<SectionState>) { markStarted(); setPrevious(sections); setSections((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  function applyPaste() {
    markStarted(); const lines = paste.trim().split(/\r?\n/).filter(Boolean); if (lines.length !== sections.length) { sendPanelEvent({ name: "mock_exam_import_failed", properties: { examType, reason: "ROW_COUNT" } }); return setStatus(`${sections.length} satır bekleniyor.`); }
    const parsedLines = lines.map((line) => line.trim().split(/[\t;, ]+/).map(Number));
    if (parsedLines.some((values) => values.length < 3 || values.length > 4 || values.some((value) => !Number.isInteger(value) || value < 0))) { sendPanelEvent({ name: "mock_exam_import_failed", properties: { examType, reason: "FORMAT" } }); return setStatus("Her satırda 3 veya 4 negatif olmayan tam sayı olmalı."); }
    if (parsedLines.some((values, index) => values[0] + values[1] + values[2] !== mockExamTemplates[examType].sections[index].questions)) { sendPanelEvent({ name: "mock_exam_import_failed", properties: { examType, reason: "TOTAL_MISMATCH" } }); return setStatus("Yapıştırılan satırlardan birinin soru toplamı şablonla eşleşmiyor."); }
    const next = parsedLines.map((values, index) => ({ ...sections[index], correctCount: values[0], incorrectCount: values[1], blankCount: values[2], durationMinutes: values[3] || 0 }));
    setPrevious(sections); setSections(next); setPasteApplied(true); setStatus("Toplu değerler uygulandı; toplamları kontrol edin.");
  }
  function toggleReason(index: number, category: MockExamErrorCategory) {
    markStarted(); const selectedCount = sections.reduce((sum, item) => sum + item.errorCategories.length, 0); const has = sections[index].errorCategories.includes(category);
    if (!has && selectedCount >= 3) return setStatus("Bir deneme için en fazla üç hata nedeni seçebilirsiniz.");
    updateSection(index, { errorCategories: has ? sections[index].errorCategories.filter((item) => item !== category) : [...sections[index].errorCategories, category] });
  }
  async function submit() {
    markStarted(); setSaving(true); setStatus("");
    try {
      const response = await fetch("/api/panel/mock-exams", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ studentId: role === "STUDENT" ? undefined : studentId, exam: examType, title, publisher, takenAt: new Date(`${takenAt}T12:00:00`).toISOString(), durationMinutes, entryDurationMs: startedAt.current ? Date.now() - startedAt.current : 0, source: pasteApplied ? "PASTE" : "MANUAL", sections: sections.map((section) => ({ ...section, durationMinutes: section.durationMinutes || null })) }) });
      const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Deneme kaydedilemedi.");
      setExams((current) => [body.exam as MockExamView, ...current]); setStatus("Deneme kaydedildi. Analiz yeni kayıtla güncellendi."); setTitle(""); setPublisher(""); started.current = false; startedAt.current = null; setPasteApplied(false);
    } catch (error) { setStatus(error instanceof Error ? error.message : "Deneme kaydedilemedi."); } finally { setSaving(false); }
  }
  async function approveAction(examId: string, action: string) {
    const target = exams.find((exam) => exam.id === examId); if (!target) return;
    const response = await fetch(`/api/panel/mock-exams/${examId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ reasons: target.sections.map((section) => ({ sectionId: section.id, categories: section.errors })), nextAction: action }) });
    if (!response.ok) return setStatus((await response.json().catch(() => ({}))).error || "Eylem onaylanamadı.");
    setExams((current) => current.map((exam) => exam.id === examId ? { ...exam, nextAction: action } : exam)); setStatus("Sonraki küçük eylem öğretmen tarafından onaylandı.");
  }

  return <div className="space-y-6">
    {canCreate ? <section className="panel-surface p-5" onFocus={markStarted}><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-extrabold">Hızlı deneme girişi</h2><p className="mt-1 text-xs leading-5 text-[var(--site-muted)]">Doğru–yanlış–boş ve süreyi girin. Soru metni veya görseli yüklenmez.</p></div><TimerReset size={19} className="text-[var(--brand-olive)]" /></div>
      <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{role !== "STUDENT" ? <label className="panel-field">Öğrenci<select value={studentId} onChange={(event) => setStudentId(event.target.value)}>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label> : null}<label className="panel-field">Sınav<select value={examType} onChange={(event) => changeExam(event.target.value as CurriculumExam)}>{Object.keys(mockExamTemplates).map((exam) => <option key={exam} value={exam}>{exam}</option>)}</select></label><label className="panel-field">Tarih<input type="date" value={takenAt} onChange={(event) => setTakenAt(event.target.value)} /></label><label className="panel-field">Toplam süre (dk)<input inputMode="numeric" type="number" min={1} max={600} value={durationMinutes} onChange={(event) => setDurationMinutes(Number(event.target.value))} /></label><label className="panel-field">Deneme adı (isteğe bağlı)<input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} /></label><label className="panel-field">Yayın (isteğe bağlı)<input value={publisher} maxLength={120} onChange={(event) => setPublisher(event.target.value)} /></label></div>
      <details className="mt-4 rounded-2xl border border-[var(--site-line)] p-4"><summary className="cursor-pointer text-xs font-bold"><ClipboardPaste size={14} className="mr-2 inline" /> CSV / tablo değerlerini toplu yapıştır</summary><p className="mt-2 text-[10.5px] text-[var(--site-muted)]">Her bölüm için ayrı satır: doğru yanlış boş süre. Sekme, boşluk, virgül veya noktalı virgül kullanılabilir.</p><textarea className="mt-3 min-h-24 w-full rounded-xl border border-[var(--site-line)] p-3 font-mono text-xs" value={paste} onChange={(event) => setPaste(event.target.value)} /><button type="button" onClick={applyPaste} className="panel-quick-action mt-2">Değerleri uygula</button></details>
      <div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-xs"><thead><tr className="text-[10px] uppercase tracking-wide text-[var(--site-muted)]"><th className="pb-2">Bölüm</th><th>Doğru</th><th>Yanlış</th><th>Boş</th><th>Süre</th><th>Kontrol</th></tr></thead><tbody>{sections.map((section, index) => { const template = mockExamTemplates[examType].sections[index]; const total = section.correctCount + section.incorrectCount + section.blankCount; return <tr key={section.subjectCode} className="border-t border-[var(--site-line)]"><th className="py-3 pr-3">{template.name}<span className="ml-2 text-[10px] text-[var(--site-muted)]">/{template.questions}</span></th>{(["correctCount", "incorrectCount", "blankCount", "durationMinutes"] as const).map((field) => <td key={field} className="pr-2"><input aria-label={`${template.name} ${field}`} className="w-20 rounded-xl border border-[var(--site-line)] px-2 py-2" inputMode="numeric" type="number" min={0} value={section[field]} onChange={(event) => updateSection(index, { [field]: Number(event.target.value) })} /></td>)}<td className={total === template.questions ? "font-bold text-emerald-700" : "font-bold text-rose-700"}>{total}/{template.questions}</td></tr>; })}</tbody></table></div>
      <div className="mt-5"><h3 className="text-xs font-extrabold">En fazla üç hata nedeni</h3><p className="mt-1 text-[10.5px] text-[var(--site-muted)]">Öğrenci seçebilir; öğretmen daha sonra düzeltebilir. Bir “başarısızlık etiketi” değildir.</p><div className="mt-3 space-y-3">{sections.map((section, index) => <div key={section.subjectCode} className="rounded-2xl bg-[var(--site-bg-warm)] p-3"><p className="mb-2 text-[10.5px] font-bold">{mockExamTemplates[examType].sections[index].name}</p><div className="flex flex-wrap gap-2">{Object.entries(mockExamErrorLabels).map(([value, label]) => <label key={value} className="inline-flex items-center gap-2 rounded-full border border-[var(--site-line)] bg-white px-3 py-2 text-[10.5px] font-bold"><input type="checkbox" checked={section.errorCategories.includes(value as MockExamErrorCategory)} onChange={() => toggleReason(index, value as MockExamErrorCategory)} />{label}</label>)}</div></div>)}</div></div>
      <div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" disabled={saving || (role !== "STUDENT" && !studentId)} onClick={() => void submit()} className="panel-primary-button"><Save size={15} /> {saving ? "Kaydediliyor…" : "Denemeyi kaydet"}</button>{previous ? <button type="button" onClick={() => { setSections(previous); setPrevious(null); }} className="panel-secondary-button"><RotateCcw size={14} /> Son değişikliği geri al</button> : null}{status ? <p role="status" className="text-xs font-bold text-[var(--site-body)]">{status}</p> : null}</div>
    </section> : null}
    <section className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><article className="panel-surface p-5"><h2 className="text-sm font-extrabold">Kişisel hata eğilimi</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Sonuçlar yalnız öğrencinin kendi denemeleriyle karşılaştırılır.</p><div className="mt-4 overflow-x-auto"><table className="min-w-[620px] w-full text-xs"><thead><tr><th className="pb-2 text-left">Bölüm</th>{Object.values(mockExamErrorLabels).map((label) => <th key={label} className="px-2 pb-2 text-center text-[9px] text-[var(--site-muted)]">{label}</th>)}</tr></thead><tbody>{trend.heatmap.map((row) => <tr key={row.key} className="border-t border-[var(--site-line)]"><th className="py-3 text-left">{row.subject}</th>{Object.keys(mockExamErrorLabels).map((category) => { const count = row.categories[category as MockExamErrorCategory]; return <td key={category} className="px-2 text-center"><span className={`inline-grid h-8 w-8 place-items-center rounded-lg font-extrabold ${count >= 3 ? "bg-amber-200 text-amber-950" : count === 2 ? "bg-amber-100 text-amber-900" : count === 1 ? "bg-[#eef3e9] text-[var(--brand-olive)]" : "bg-slate-50 text-slate-400"}`}>{count}</span></td>; })}</tr>)}{!trend.heatmap.length ? <tr><td colSpan={6} className="py-8 text-center text-[var(--site-muted)]">İlk deneme kaydedildiğinde eğilim oluşacak.</td></tr> : null}</tbody></table></div></article>
      <article className="panel-surface p-5"><h2 className="text-sm font-extrabold">Sonraki küçük eylem</h2>{trend.recurringError ? <div className="mt-4 rounded-2xl bg-[#fff9dc] p-4"><p className="text-[10px] font-extrabold uppercase text-amber-800">{mockExamErrorLabels[trend.recurringError.category]} · son 3 denemede {trend.recurringError.count} işaret</p><p className="mt-2 text-xs font-bold leading-5 text-amber-950">{trend.recurringError.action}</p>{canReview && visibleExams[0] && !visibleExams[0].nextAction ? <button type="button" onClick={() => void approveAction(visibleExams[0].id, trend.recurringError!.action)} className="mt-3 rounded-xl bg-amber-900 px-3 py-2 text-[10.5px] font-bold text-white"><CheckCircle2 size={13} className="mr-1 inline" /> Öğretmen olarak onayla</button> : null}</div> : <p className="mt-4 rounded-2xl bg-slate-50 p-4 text-xs text-[var(--site-muted)]">Tekrarlayan bir neden oluştuğunda burada yalnız bir uygulanabilir adım gösterilecek.</p>}</article></section>
    <section className="panel-surface p-5"><h2 className="text-sm font-extrabold">Son denemeler</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{visibleExams.map((exam) => { const net = exam.sections.reduce((sum, section) => sum + sectionNet(exam.exam, section.correctCount, section.incorrectCount), 0); return <article key={exam.id} className="rounded-2xl border border-[var(--site-line)] p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] font-extrabold text-[var(--brand-olive)]">{exam.exam} · {new Intl.DateTimeFormat("tr-TR").format(new Date(exam.takenAt))}</span><h3 className="mt-1 text-xs font-bold">{exam.title || "Adsız deneme"}{exam.publisher ? ` · ${exam.publisher}` : ""}</h3></div><span className="rounded-full bg-[var(--brand-olive-soft)] px-2.5 py-1 text-xs font-extrabold text-[var(--brand-olive)]">{net.toLocaleString("tr-TR")} net</span></div><p className="mt-3 text-[10.5px] text-[var(--site-muted)]">{exam.sections.reduce((sum, section) => sum + section.correctCount, 0)} doğru · {exam.sections.reduce((sum, section) => sum + section.incorrectCount, 0)} yanlış · {exam.sections.reduce((sum, section) => sum + section.blankCount, 0)} boş{exam.durationMinutes ? ` · ${exam.durationMinutes} dk` : ""}</p>{exam.nextAction ? <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-[10.5px] font-bold leading-5 text-emerald-900">Öğretmen onaylı adım: {exam.nextAction}</p> : null}{role === "STUDENT" || canReview ? <ReasonEditor exam={exam} onSaved={(sections) => setExams((current) => current.map((item) => item.id === exam.id ? { ...item, sections } : item))} /> : null}</article>; })}{!visibleExams.length ? <p className="text-sm text-[var(--site-muted)]">Henüz deneme kaydı yok.</p> : null}</div></section>
  </div>;
}

function ReasonEditor({ exam, onSaved }: { exam: MockExamView; onSaved: (sections: MockExamView["sections"]) => void }) {
  const [values, setValues] = useState(() => Object.fromEntries(exam.sections.map((section) => [section.id, section.errors])) as Record<string, MockExamErrorCategory[]>);
  const [message, setMessage] = useState("");
  function toggle(sectionId: string, category: MockExamErrorCategory) {
    const has = values[sectionId].includes(category); const count = Object.values(values).reduce((sum, categories) => sum + categories.length, 0);
    if (!has && count >= 3) return setMessage("En fazla üç neden seçilebilir.");
    setValues((current) => ({ ...current, [sectionId]: has ? current[sectionId].filter((item) => item !== category) : [...current[sectionId], category] })); setMessage("");
  }
  async function save() {
    const response = await fetch(`/api/panel/mock-exams/${exam.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ reasons: exam.sections.map((section) => ({ sectionId: section.id, categories: values[section.id] })) }) });
    if (!response.ok) return setMessage((await response.json().catch(() => ({}))).error || "Nedenler kaydedilemedi.");
    onSaved(exam.sections.map((section) => ({ ...section, errors: values[section.id] }))); setMessage("Hata nedenleri kaydedildi; değişiklik audit izine alındı.");
  }
  return <details className="mt-3 border-t border-[var(--site-line)] pt-3"><summary className="cursor-pointer text-[10.5px] font-bold">Hata nedenlerini gözden geçir</summary><div className="mt-3 space-y-3">{exam.sections.map((section) => <div key={section.id}><p className="text-[10px] font-bold text-[var(--site-muted)]">{section.subjectName}</p><div className="mt-1 flex flex-wrap gap-1.5">{Object.entries(mockExamErrorLabels).map(([category, label]) => <button type="button" key={category} onClick={() => toggle(section.id, category as MockExamErrorCategory)} className={`rounded-full border px-2.5 py-1.5 text-[9.5px] font-bold ${values[section.id].includes(category as MockExamErrorCategory) ? "border-[var(--brand-olive)] bg-[var(--brand-olive-soft)] text-[var(--brand-olive)]" : "border-[var(--site-line)] bg-white"}`}>{label}</button>)}</div></div>)}</div><button type="button" onClick={() => void save()} className="panel-secondary-button mt-3">Nedenleri kaydet</button>{message ? <p role="status" className="mt-2 text-[10.5px] font-bold">{message}</p> : null}</details>;
}
