"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { checkInLabels } from "@/lib/student-check-in";

type History = { id: string; groupName: string; energy: keyof typeof checkInLabels.energy; confidence: keyof typeof checkInLabels.confidence; barrier: keyof typeof checkInLabels.barrier; shared: boolean; createdAt: string; request: null | { id: string; status: "OPEN" | "RESPONDED" | "CLOSED"; version: number; helpful: boolean | null; action: keyof typeof checkInLabels.action | null } };

export function StudentCheckInForm({ groups, history, remaining }: { groups: { id: string; name: string; subject: string }[]; history: History[]; remaining: number }) {
  const router = useRouter();
  const [groupId, setGroupId] = useState(groups[0]?.id || "");
  const [energy, setEnergy] = useState<keyof typeof checkInLabels.energy>("STEADY");
  const [confidence, setConfidence] = useState<keyof typeof checkInLabels.confidence>("BUILDING");
  const [barrier, setBarrier] = useState<keyof typeof checkInLabels.barrier>("NONE");
  const [share, setShare] = useState(false); const [help, setHelp] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit() { setBusy(true); setMessage(""); const response = await fetch("/api/panel/student-check-ins", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ groupId, energy, confidence, barrier, shareWithTeacher: share || help, helpRequested: help }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) return setMessage(data.error || "Check-in kaydedilemedi."); setMessage("Check-in kaydedildi."); router.refresh(); }
  async function feedback(id: string, version: number, helpful: boolean) { setBusy(true); const response = await fetch(`/api/panel/student-help-requests/${id}/feedback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: version, helpful }) }); const data = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) return setMessage(data.error || "Geri bildirim kaydedilemedi."); router.refresh(); }
  const options = <T extends string>(values: Record<T, string>, selected: T, setSelected: (value: T) => void) => <div className="grid gap-2 sm:grid-cols-3">{Object.entries(values).map(([value, label]) => <button key={value} type="button" aria-pressed={selected === value} onClick={() => setSelected(value as T)} className={`rounded-2xl border p-3 text-left text-xs font-bold ${selected === value ? "border-[var(--brand-olive)] bg-[var(--panel-nav-active)]" : "border-[var(--site-line)] bg-white"}`}>{label as string}</button>)}</div>;
  return <div className="space-y-6">
    <section className="panel-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-extrabold">60 saniyelik check-in</h2><span className="rounded-full bg-[var(--panel-nav-active)] px-3 py-1 text-xs font-bold">Bu hafta {remaining} hak</span></div>
      <p className="mt-2 text-sm text-[var(--site-body)]">Bu bir sınav, tanı veya puan değildir. Nasıl ilerlediğini anlamana yardımcı olur.</p>
      <div className="mt-5 space-y-5"><label className="block text-xs font-extrabold">Hangi grup?<select aria-label="Check-in grubu" className="panel-input mt-2" value={groupId} onChange={(event) => setGroupId(event.target.value)}>{groups.map((group) => <option key={group.id} value={group.id}>{group.name} · {group.subject}</option>)}</select></label>
        <fieldset><legend className="mb-2 text-xs font-extrabold">Enerjin nasıl?</legend>{options(checkInLabels.energy, energy, setEnergy)}</fieldset>
        <fieldset><legend className="mb-2 text-xs font-extrabold">Çalışmana güvenin nasıl?</legend>{options(checkInLabels.confidence, confidence, setConfidence)}</fieldset>
        <fieldset><legend className="mb-2 text-xs font-extrabold">Şu anki çalışma engelin</legend>{options(checkInLabels.barrier, barrier, setBarrier)}</fieldset>
        <label className="flex items-start gap-3 rounded-2xl border border-[var(--site-line)] p-3 text-sm"><input type="checkbox" checked={share || help} disabled={help} onChange={(event) => setShare(event.target.checked)} className="mt-1" /><span><b>Öğretmenim görsün</b><span className="block text-xs text-[var(--site-muted)]">Kapalıysa yalnız sen görürsün. Veliye hiçbir durumda gösterilmez.</span></span></label>
        <label className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm"><input type="checkbox" checked={help} onChange={(event) => { setHelp(event.target.checked); if (event.target.checked) setShare(true); }} className="mt-1" /><span><b>Öğretmenimden yardım istiyorum</b><span className="block text-xs text-amber-900">Öğretmenine bildirim gider; 24 saat içinde küçük bir destek adımı hedeflenir.</span></span></label>
        <div className="rounded-2xl bg-rose-50 p-3 text-xs leading-5 text-rose-900"><b>Acil durum alanı değildir.</b> Kendine veya başkasına zarar verme riski varsa 112’yi ara ve güvendiğin bir yetişkine hemen söyle.</div>
        {message ? <p role="status" className="text-sm font-bold">{message}</p> : null}<button type="button" disabled={busy || remaining < 1 || !groupId} onClick={submit} className="panel-primary-button w-full sm:w-auto">{busy ? "Kaydediliyor…" : "Check-in'i kaydet"}</button>
      </div></section>
    <section><h2 className="text-lg font-extrabold">Geçmişim</h2><div className="mt-3 grid gap-3">{history.length ? history.map((item) => <article key={item.id} className="panel-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.groupName}</b><span className="text-xs text-[var(--site-muted)]">{new Date(item.createdAt).toLocaleDateString("tr-TR")} · {item.shared ? "Öğretmenle paylaşıldı" : "Yalnız bende"}</span></div><p className="mt-2 text-sm">{checkInLabels.energy[item.energy]} · {checkInLabels.confidence[item.confidence]} · {checkInLabels.barrier[item.barrier]}</p>{item.request ? <div className="mt-3 rounded-2xl bg-[var(--panel-nav-active)] p-3 text-sm"><b>{item.request.status === "OPEN" ? "Öğretmen yanıtı bekleniyor" : item.request.status === "CLOSED" ? "Destek tamamlandı" : "Öğretmenin destek adımı"}</b>{item.request.action ? <p className="mt-1">{checkInLabels.action[item.request.action]}</p> : null}{item.request.status === "RESPONDED" && item.request.helpful === null ? <div className="mt-3 flex gap-2"><button disabled={busy} onClick={() => feedback(item.request!.id, item.request!.version, true)} className="panel-primary-button text-xs">İşime yaradı</button><button disabled={busy} onClick={() => feedback(item.request!.id, item.request!.version, false)} className="panel-secondary-button text-xs">Henüz değil</button></div> : null}</div> : null}</article>) : <p className="text-sm text-[var(--site-muted)]">Henüz check-in yok.</p>}</div></section>
  </div>;
}
