"use client";

import { useState } from "react";
import { Check, Pencil, Target } from "lucide-react";

export function StudentWeeklyGoal({ initial }: { initial: string }) {
  const [goal, setGoal] = useState(initial); const [draft, setDraft] = useState(initial); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  return <section className="rounded-[24px] border border-[#eadf9e] bg-[#fff9dc] p-5"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.06em] text-amber-800"><Target size={15} /> Bu haftaki kişisel hedefim</span><button type="button" onClick={() => { setDraft(goal); setEditing(!editing); setMessage(""); }} className="rounded-full bg-white p-2 text-amber-800" aria-label="Haftalık hedefi düzenle"><Pencil size={14} /></button></div>
    {editing ? <form className="mt-4" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch("/api/panel/student/weekly-goal", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ goal: draft }) }); const body = await response.json().catch(() => ({})); setBusy(false); if (!response.ok) return setMessage(body.error || "Hedef kaydedilemedi."); setGoal(body.goal); setEditing(false); setMessage("Hedefin kaydedildi."); }}><textarea value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={180} className="panel-input min-h-24 resize-none" aria-label="Haftalık hedef" /><div className="mt-3 flex items-center justify-between gap-3"><span className="text-[10.5px] text-amber-900/65">{draft.length}/180</span><button disabled={busy || draft.trim().length < 3} className="panel-quick-action panel-quick-action-primary"><Check size={14} /> {busy ? "Kaydediliyor" : "Hedefi kaydet"}</button></div></form> : <p className="mt-4 text-base font-semibold leading-7 text-amber-950">{goal}</p>}<p aria-live="polite" className="mt-2 text-xs font-bold text-emerald-700">{message}</p></section>;
}
