"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { checkInLabels } from "@/lib/student-check-in";

type Row = { id: string; studentName: string; groupName: string; energy: keyof typeof checkInLabels.energy; confidence: keyof typeof checkInLabels.confidence; barrier: keyof typeof checkInLabels.barrier; status: "OPEN" | "RESPONDED"; dueAt: string; version: number; helpful: boolean | null; responseAction: keyof typeof checkInLabels.action | null };
export function TeacherHelpRequests({ rows }: { rows: Row[] }) { const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState(""); const [items, setItems] = useState(rows); async function respond(row: Row, action: keyof typeof checkInLabels.action) { if (busy) return; setBusy(row.id); setMessage(""); const response = await fetch(`/api/panel/student-help-requests/${row.id}/respond`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: row.version, action }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { setBusy(null); return setMessage(data.error || "Yanıt kaydedilemedi."); } setItems((current) => current.map((item) => item.id === row.id ? { ...item, status: "RESPONDED", responseAction: action, version: item.version + 1, helpful: null } : item)); setBusy(null); router.refresh(); }
  return <div className="space-y-3">{message ? <p role="status" className="text-sm font-bold">{message}</p> : null}{items.length ? items.map((row) => <article key={row.id} className={`panel-card p-4 ${row.status === "OPEN" && new Date(row.dueAt) < new Date() ? "border-amber-300" : ""}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-extrabold">{row.studentName}</h2><p className="text-xs text-[var(--site-muted)]">{row.groupName}</p></div><span className="rounded-full bg-[var(--panel-nav-active)] px-3 py-1 text-xs font-bold">{row.status === "OPEN" ? (new Date(row.dueAt) < new Date() ? "24 saat geçti" : "Yanıt bekliyor") : row.helpful === false ? "Yeni adım bekliyor" : "Yanıtlandı"}</span></div><p className="mt-3 text-sm">{checkInLabels.energy[row.energy]} · {checkInLabels.confidence[row.confidence]}</p><p className="mt-1 text-sm font-bold">Engel: {checkInLabels.barrier[row.barrier]}</p>{row.responseAction ? <p className="mt-3 rounded-xl bg-[var(--panel-nav-active)] p-3 text-sm">Son adım: {checkInLabels.action[row.responseAction]}</p> : null}{row.status === "OPEN" ? <div className="mt-4"><p className="mb-2 text-xs font-extrabold">Taahhüt edebileceğiniz küçük destek adımı</p><div className="grid gap-2 sm:grid-cols-2">{Object.entries(checkInLabels.action).map(([action, label]) => <button type="button" disabled={busy === row.id} onClick={() => respond(row, action as keyof typeof checkInLabels.action)} key={action} className="panel-secondary-button text-left text-xs">{label}</button>)}</div></div> : null}</article>) : <div className="panel-card p-6 text-sm text-[var(--site-muted)]">Yanıt bekleyen yardım isteği yok.</div>}</div>;
}
