"use client";

import { useState } from "react";
import { PackageCheck, RefreshCcw, Send } from "lucide-react";

type Row = { attendanceId: string; studentName: string; lessonTitle: string; lessonDate: string; status: "ABSENT" | "EXCUSED"; package: null | { id: string; status: "DRAFT" | "PUBLISHED" | "COMPLETED"; version: number; summaryTopic: string; summaryNextStep: string; checkpointPrompt: string; dueAt: string; items: { id: string; kind: "MATERIAL" | "ASSIGNMENT"; title: string }[] } };

export function TeacherRecoveryManager({ rows }: { rows: Row[] }) {
  const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function generate(row: Row) { setBusy(row.attendanceId); setMessage(""); const response = await fetch("/api/panel/recovery-packages/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ attendanceId: row.attendanceId }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.error || "Paket hazırlanamadı."); setBusy(null); return; } window.location.reload(); }
  async function publish(row: Row) { if (!row.package) return; setBusy(row.package.id); setMessage(""); const response = await fetch(`/api/panel/recovery-packages/${row.package.id}/publish`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: row.package.version }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.error || "Paket yayınlanamadı."); setBusy(null); return; } setMessage(body.planRebalanced ? "Paket yayınlandı; onaylı haftalık plan kapasite sınırlarıyla yeniden dengelendi." : "Paket öğrenciye yayınlandı."); window.location.reload(); }
  return <div><p aria-live="polite" className="mb-4 text-sm font-bold text-[var(--brand-olive)]">{message}</p><div className="space-y-4">{rows.map((row) => <article key={row.attendanceId} className="panel-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[.06em] text-[var(--brand-olive)]">{row.status === "ABSENT" ? "Katılmadı" : "Mazeretli"} · {new Date(row.lessonDate).toLocaleDateString("tr-TR")}</p><h2 className="mt-1 text-lg font-extrabold">{row.studentName}</h2><p className="mt-1 text-sm text-[var(--site-muted)]">{row.lessonTitle}</p></div><span className="rounded-full bg-[var(--site-bg-warm)] px-3 py-1 text-[11px] font-extrabold">{row.package ? row.package.status === "DRAFT" ? "Önizleme" : row.package.status === "PUBLISHED" ? "Öğrencide" : "Tamamlandı" : "Paket bekliyor"}</span></div>{row.package ? <div className="mt-4 rounded-2xl border border-[var(--site-line)] bg-white p-4"><p className="text-[11px] font-extrabold uppercase text-[var(--site-muted)]">Öğrencinin göreceği önizleme</p><h3 className="mt-2 text-base font-extrabold">{row.package.summaryTopic}</h3><p className="mt-2 text-sm leading-6">Sonraki küçük adım: {row.package.summaryNextStep}</p><ul className="mt-3 space-y-1 text-xs text-[var(--site-body)]">{row.package.items.map((item) => <li key={item.id}>• {item.kind === "MATERIAL" ? "Kaynak" : "Çalışma"}: {item.title}</li>)}</ul><p className="mt-3 text-xs font-bold text-[var(--brand-olive)]">Mini kontrol: {row.package.checkpointPrompt}</p><p className="mt-2 text-[11px] text-[var(--site-muted)]">Hedef: {new Date(row.package.dueAt).toLocaleString("tr-TR")} · Öğrenciye özel ders notu ve yoklama notu pakete alınmaz.</p></div> : null}<div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={busy !== null || row.package?.status !== undefined && row.package.status !== "DRAFT"} onClick={() => generate(row)} className="panel-quick-action"><RefreshCcw size={14} /> {row.package ? "Taslağı güvenle yenile" : "Telafi taslağı hazırla"}</button>{row.package?.status === "DRAFT" ? <button type="button" disabled={busy !== null} onClick={() => publish(row)} className="panel-quick-action panel-quick-action-primary"><Send size={14} /> Öğrenciye yayınla</button> : null}</div></article>)}{!rows.length ? <div className="panel-surface p-9 text-center"><PackageCheck className="mx-auto text-[var(--site-muted)]" /><p className="mt-3 text-sm font-bold">Son 30 günde telafi paketi bekleyen devamsızlık yok.</p></div> : null}</div></div>;
}
