"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Plus, RotateCcw } from "lucide-react";
import { sendPanelEvent } from "@/lib/panel-event-client";

type StudentRow = { id: string; name: string; activeCount: number; dueCount: number; persistentCount: number; lastReviewedAt: string | null };
function band(count: number) { return count === 0 ? "0" as const : count <= 5 ? "1-5" as const : count <= 20 ? "6-20" as const : "21+" as const; }
export function TeacherReviewMonitor({ students }: { students: StudentRow[] }) {
  const [studentId, setStudentId] = useState(students[0]?.id || ""); const [title, setTitle] = useState(""); const [sourceReference, setSourceReference] = useState(""); const [message, setMessage] = useState("");
  const totalDue = students.reduce((sum, student) => sum + student.dueCount, 0); const totalActive = students.reduce((sum, student) => sum + student.activeCount, 0);
  useEffect(() => { sendPanelEvent({ name: "review_queue_viewed", properties: { actorRole: "TEACHER", dueCountBand: band(totalDue), activeCountBand: band(totalActive) } }); }, [totalActive, totalDue]);
  async function create() { const response = await fetch("/api/panel/review-queue", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ studentId, title, sourceReference }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setMessage(body.error || "Tekrar öğesi oluşturulamadı."); setMessage("Kaynak referansı yarının küçük tekrarlarına eklendi."); setTitle(""); setSourceReference(""); }
  return <div className="space-y-5"><section className="panel-surface p-5"><h2 className="flex items-center gap-2 text-sm font-extrabold"><Plus size={16} /> Kendi materyalimden tekrar ekle</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Telifli soruyu kopyalamayın; kitap/föy ve soru numarası gibi erişilebilir bir referans verin.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="panel-field">Öğrenci<select value={studentId} onChange={(event) => setStudentId(event.target.value)}>{students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label className="panel-field">Kısa çalışma başlığı<input value={title} maxLength={140} onChange={(event) => setTitle(event.target.value)} placeholder="Örn. Köklü ifadelerde işlem sırası" /></label><label className="panel-field">Kaynak referansı<input value={sourceReference} maxLength={240} onChange={(event) => setSourceReference(event.target.value)} placeholder="Örn. Öğretmen föyü s.4, soru 6" /></label></div><div className="mt-4 flex items-center gap-3"><button disabled={!studentId || title.trim().length < 3 || sourceReference.trim().length < 2} onClick={() => void create()} className="panel-primary-button"><Plus size={14} /> Tekrar ekle</button>{message ? <p role="status" className="text-xs font-bold">{message}</p> : null}</div></section>
    <section className="panel-surface overflow-hidden"><div className="border-b border-[var(--site-line)] p-5"><h2 className="flex items-center gap-2 text-sm font-extrabold"><RotateCcw size={16} /> Kuyruk gözetimi</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Sıralama değil; yalnız büyüyen kuyruk ve kalıcı zorlanma sinyalleri.</p></div><div className="divide-y divide-[var(--site-line)]">{students.map((student) => { const needsAttention = student.activeCount > 20 || student.dueCount > 5 || student.persistentCount > 0; return <article key={student.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h3 className="text-sm font-bold">{student.name}</h3>{needsAttention ? <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-1 text-[9px] font-extrabold text-amber-900"><AlertTriangle size={11} /> İnsan bakışı gerekli</span> : null}</div><p className="mt-1 text-xs text-[var(--site-muted)]">{student.activeCount} aktif · bugün {student.dueCount} · kalıcı zorlanma {student.persistentCount}</p></div><p className="text-[10.5px] text-[var(--site-muted)]">{student.lastReviewedAt ? `Son dönüş ${new Intl.DateTimeFormat("tr-TR").format(new Date(student.lastReviewedAt))}` : "Henüz yeniden çözüm yok"}</p></article>; })}{!students.length ? <p className="p-8 text-center text-sm text-[var(--site-muted)]">Aktif öğrenciniz bulunmuyor.</p> : null}</div></section></div>;
}
