"use client";

import { useRef, useState } from "react";
import { CheckCircle2, Clock3, ListChecks } from "lucide-react";
import { sendPanelEvent } from "@/lib/panel-event-client";

type Plan = { id: string; studentName: string; status: "DRAFT" | "APPROVED" | "CHANGE_REQUESTED" | "ARCHIVED"; version: number; capacityMinutes: number; changeRequestCategory: string | null; tasks: { id: string; title: string; scheduledFor: string; durationMinutes: number; reasonCode: string }[] };
const date = new Intl.DateTimeFormat("tr-TR", { weekday: "short", day: "numeric", month: "short" });
export function TeacherPlanReview({ plans: initial }: { plans: Plan[] }) {
  const [plans, setPlans] = useState(initial); const [message, setMessage] = useState(""); const openedAt = useRef(performance.now());
  async function approve(plan: Plan) { const response = await fetch(`/api/panel/adaptive-plan/${plan.id}/approve`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedVersion: plan.version }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setMessage(body.error || "Plan onaylanamadı."); setPlans((current) => current.map((item) => item.id === plan.id ? { ...item, status: "APPROVED", version: item.version + 1 } : item)); sendPanelEvent({ name: "plan_review_completed", properties: { durationMs: Math.min(30 * 60 * 1000, Math.round(performance.now() - openedAt.current)), taskCount: plan.tasks.length, approved: true } }); setMessage(`${plan.studentName} için plan onaylandı ve kilitlendi.`); }
  if (!plans.length) return <div className="panel-surface p-8 text-center"><ListChecks className="mx-auto text-[var(--site-muted)]" /><h2 className="mt-3 font-extrabold">İncelenecek plan yok.</h2><p className="mt-1 text-sm text-[var(--site-muted)]">Öğrenci öneri oluşturduğunda burada görünür.</p></div>;
  return <div className="space-y-4">{plans.map((plan) => <article key={plan.id} className="panel-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">{plan.studentName}</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Haftalık kapasite {plan.capacityMinutes} dk · {plan.tasks.length} iş · kural adaptive-v1</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-extrabold ${plan.status === "APPROVED" ? "bg-emerald-100 text-emerald-800" : plan.status === "CHANGE_REQUESTED" ? "bg-amber-100 text-amber-900" : "bg-sky-100 text-sky-800"}`}>{plan.status === "APPROVED" ? "Onaylandı" : plan.status === "CHANGE_REQUESTED" ? "Değişiklik istendi" : "Taslak"}</span></div>{plan.changeRequestCategory ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900">Öğrenci geri bildirimi: {plan.changeRequestCategory === "TOO_MUCH" ? "Öğrenci bu haftanın yoğunluğunu fazla buldu." : plan.changeRequestCategory === "WRONG_DAYS" ? "Öğrenci çalışma günlerini değiştirmek istiyor." : plan.changeRequestCategory === "PRIORITY" ? "Öncelik sırası değişmeli." : "Başka bir neden"}</p> : null}<div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{plan.tasks.map((task) => <div key={task.id} className="rounded-xl border border-[var(--site-line)] bg-[var(--site-bg-warm)] p-3"><p className="flex items-center gap-1 text-[10px] font-bold text-[var(--site-muted)]"><Clock3 size={12} />{date.format(new Date(task.scheduledFor))} · {task.durationMinutes} dk</p><p className="mt-1 text-xs font-extrabold">{task.title}</p></div>)}</div>{plan.status === "DRAFT" ? <div className="mt-4 flex justify-end"><button type="button" onClick={() => void approve(plan)} className="panel-quick-action panel-quick-action-primary"><CheckCircle2 size={14} /> Onayla ve kilitle</button></div> : null}</article>)}<p aria-live="polite" className="text-xs font-bold text-[var(--brand-olive)]">{message}</p></div>;
}
