"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Bot, Check, Copy, Flag, ShieldCheck, X } from "lucide-react";

type Content = { title: string; body: string; checkPrompt: string; successCriteria: string[]; citations: string[] };
type Draft = { id: string; taskType: "ASSIGNMENT" | "MINI_CHECK"; status: "DRAFT" | "APPROVED" | "REJECTED" | "FLAGGED"; provider: "OPENAI" | "GEMINI" | "FALLBACK" | "STUB"; promptVersion: string; modelName: string | null; fallbackReason: string | null; version: number; createdAt: string; lessonTitle: string; sourceRefs: Array<{ id: string; label: string }>; originalContent: Content; reviewedContent: Content | null };

function DraftCard({ draft, onReviewed }: { draft: Draft; onReviewed: (draft: Draft) => void }) {
  const router = useRouter(); const shown = draft.reviewedContent || draft.originalContent;
  const [content, setContent] = useState({ title: shown.title, body: shown.body, checkPrompt: shown.checkPrompt, successCriteria: shown.successCriteria });
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [flagReason, setFlagReason] = useState("FACTUAL_ERROR");
  const changed = JSON.stringify(content) !== JSON.stringify({ title: draft.originalContent.title, body: draft.originalContent.body, checkPrompt: draft.originalContent.checkPrompt, successCriteria: draft.originalContent.successCriteria });
  async function review(action: "APPROVE" | "REJECT" | "FLAG") {
    if (busy) return;
    setBusy(true); setMessage("");
    const response = await fetch(`/api/panel/ai-drafts/${draft.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, expectedVersion: draft.version, content: action === "APPROVE" ? content : undefined, flagReason: action === "FLAG" ? flagReason : undefined }) });
    const body = await response.json().catch(() => ({})); setBusy(false);
    if (!response.ok) return setMessage(body.error || "İnceleme kaydedilemedi.");
    onReviewed({ ...draft, status: body.status, version: body.version, reviewedContent: action === "APPROVE" ? { ...content, citations: draft.originalContent.citations } : null });
    setMessage(action === "APPROVE" ? "İnsan onayı kaydedildi. İçerik otomatik yayınlanmadı." : action === "FLAG" ? "Hata işaretlendi; taslak kullanılmayacak." : "Taslak reddedildi.");
    router.refresh();
  }
  return <article className="rounded-[14px] border border-[var(--site-line)] bg-white p-5 shadow-[var(--panel-card-shadow)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-extrabold text-violet-700">{draft.taskType === "ASSIGNMENT" ? "Ödev taslağı" : "Mini kontrol"}</span><span className={`rounded-full px-2 py-1 text-[10px] font-extrabold ${draft.status === "APPROVED" ? "bg-emerald-100 text-emerald-800" : draft.status === "DRAFT" ? "bg-amber-100 text-amber-900" : "bg-slate-100 text-slate-700"}`}>{draft.status === "APPROVED" ? "Öğretmen onaylı" : draft.status === "DRAFT" ? "İnceleme bekliyor" : draft.status === "FLAGGED" ? "Hatalı işaretlendi" : "Reddedildi"}</span>{changed && draft.status === "DRAFT" ? <span className="rounded-full bg-sky-100 px-2 py-1 text-[10px] font-extrabold text-sky-800">Düzenlendi</span> : null}</div><p className="mt-2 text-xs font-bold text-[var(--site-muted)]">{draft.lessonTitle} · {draft.promptVersion} · {draft.provider === "OPENAI" || draft.provider === "GEMINI" ? draft.modelName : draft.provider === "STUB" ? "Güvenli test sağlayıcısı" : "Modelsiz güvenli yedek"}</p></div></div>
    {draft.fallbackReason ? <p className="mt-4 flex gap-2 rounded-2xl bg-amber-50 p-3 text-xs leading-5 text-amber-950"><ShieldCheck size={16} className="mt-0.5 shrink-0" /> Dış model kullanılmadı: {draft.fallbackReason}. Kaynaklı kural taslağı gösteriliyor.</p> : null}
    <div className="mt-4 grid gap-3"><label className="text-xs font-extrabold">Başlık<input disabled={draft.status !== "DRAFT"} value={content.title} onChange={(event) => setContent((current) => ({ ...current, title: event.target.value }))} maxLength={140} className="panel-input mt-1" /></label><label className="text-xs font-extrabold">Yönerge<textarea disabled={draft.status !== "DRAFT"} value={content.body} onChange={(event) => setContent((current) => ({ ...current, body: event.target.value }))} maxLength={1200} className="panel-input mt-1 min-h-28 resize-y" /></label><label className="text-xs font-extrabold">Kısa kontrol sorusu<textarea disabled={draft.status !== "DRAFT"} value={content.checkPrompt} onChange={(event) => setContent((current) => ({ ...current, checkPrompt: event.target.value }))} maxLength={300} className="panel-input mt-1 min-h-20 resize-y" /></label><div><p className="text-xs font-extrabold">Başarı ölçütleri</p>{content.successCriteria.map((criterion, index) => <input key={index} disabled={draft.status !== "DRAFT"} aria-label={`Başarı ölçütü ${index + 1}`} value={criterion} onChange={(event) => setContent((current) => ({ ...current, successCriteria: current.successCriteria.map((item, itemIndex) => itemIndex === index ? event.target.value : item) }))} maxLength={160} className="panel-input mt-1 text-xs" />)}</div></div>
    <div className="mt-4 rounded-2xl bg-[var(--site-bg-warm)] p-3"><p className="text-[11px] font-extrabold">Kullanılan kaynaklar</p><div className="mt-2 flex flex-wrap gap-1">{draft.originalContent.citations.map((citation) => <span key={citation} className="rounded-full bg-white px-2 py-1 text-[10px] font-bold">{draft.sourceRefs.find((item) => item.id === citation)?.label || citation}</span>)}</div></div>
    {draft.status === "DRAFT" ? <div className="mt-4"><p className="flex gap-2 text-xs leading-5 text-rose-800"><AlertTriangle size={15} className="mt-0.5 shrink-0" /> Kaynakları ve matematiksel doğruluğu kontrol etmeden onaylamayın. Onay, öğrenci veya veliye yayın yapmaz.</p><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} type="button" onClick={() => void review("APPROVE")} className="panel-quick-action panel-quick-action-primary"><Check size={14} /> {changed ? "Düzenleyip onayla" : "Kontrol ettim, onayla"}</button><button disabled={busy} type="button" onClick={() => void review("REJECT")} className="panel-quick-action"><X size={14} /> Reddet</button><select aria-label="AI hata nedeni" value={flagReason} onChange={(event) => setFlagReason(event.target.value)} className="panel-input w-auto text-xs"><option value="FACTUAL_ERROR">Bilgi/çözüm hatası</option><option value="UNSUPPORTED_CITATION">Kaynak desteklemiyor</option><option value="UNSAFE_TONE">Uygunsuz ton</option><option value="PRIVACY">Gizlilik riski</option><option value="OTHER">Başka kontrollü hata</option></select><button disabled={busy} type="button" onClick={() => void review("FLAG")} className="panel-quick-action text-rose-700"><Flag size={14} /> Hatalı işaretle</button></div></div> : draft.status === "APPROVED" ? <button type="button" onClick={() => void navigator.clipboard.writeText(`${content.title}\n\n${content.body}\n\nKontrol: ${content.checkPrompt}\n\nÖlçütler:\n- ${content.successCriteria.join("\n- ")}`).then(() => setMessage("Onaylı taslak panoya kopyalandı."))} className="panel-quick-action mt-4"><Copy size={14} /> Onaylı taslağı kopyala</button> : null}
    {message ? <p aria-live="polite" className="mt-3 text-xs font-bold text-[var(--brand-olive)]">{message}</p> : null}</article>;
}

export function TeacherAiDrafts({ lessons, drafts }: { lessons: Array<{ id: string; title: string; groupName: string; startsAt: string }>; drafts: Draft[] }) {
  const router = useRouter(); const [lessonId, setLessonId] = useState(lessons[0]?.id || ""); const [taskType, setTaskType] = useState<"ASSIGNMENT" | "MINI_CHECK">("ASSIGNMENT"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [items, setItems] = useState(drafts);
  async function generate() { if (busy) return; setBusy(true); setMessage(""); const response = await fetch("/api/panel/ai-drafts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ lessonId, taskType, requestKey: crypto.randomUUID() }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setBusy(false); return setMessage(body.error || "Taslak üretilemedi."); } const lesson = lessons.find((item) => item.id === lessonId); const created = { ...body.draft, createdAt: String(body.draft.createdAt), lessonTitle: lesson?.title || "Ders", sourceRefs: body.draft.sourceRefs || [], originalContent: body.draft.originalContent, reviewedContent: body.draft.reviewedContent || null } as Draft; setItems((current) => current.some((item) => item.id === created.id) ? current : [created, ...current]); setMessage("Taslak hazır. Kaynakları ve içeriği kontrol edin."); setBusy(false); router.refresh(); }
  const reviewed = (next: Draft) => setItems((current) => current.map((item) => item.id === next.id ? next : item));
  return <div className="grid gap-5 xl:grid-cols-[340px_minmax(0,1fr)]"><section className="panel-surface h-fit p-5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-100 text-violet-700"><Bot size={19} /></span><h2 className="mt-4 font-extrabold">Dar görevli taslak</h2><p className="mt-1 text-xs leading-5 text-[var(--site-muted)]">Yalnız ortak ders alanları ve görünür kazanımlar kullanılır. Öğrenciye özel veri gönderilmez.</p><label className="mt-4 block text-xs font-extrabold">Kaynak ders<select value={lessonId} onChange={(event) => setLessonId(event.target.value)} className="panel-input mt-1"><option value="">Ders seçin</option>{lessons.map((lesson) => <option key={lesson.id} value={lesson.id}>{lesson.groupName} · {lesson.title}</option>)}</select></label><label className="mt-3 block text-xs font-extrabold">Taslak türü<select value={taskType} onChange={(event) => setTaskType(event.target.value as typeof taskType)} className="panel-input mt-1"><option value="ASSIGNMENT">Ödev taslağı</option><option value="MINI_CHECK">Mini kontrol</option></select></label><button disabled={busy || !lessonId} type="button" onClick={() => void generate()} className="site-btn site-btn-primary site-btn-sm mt-4 w-full">{busy ? "Güvenle hazırlanıyor" : "Kaynaklı taslak hazırla"}</button>{message ? <p aria-live="polite" className="mt-3 text-xs font-bold text-[var(--brand-olive)]">{message}</p> : null}<p className="mt-4 border-t border-[var(--site-line)] pt-4 text-[10px] leading-4 text-[var(--site-muted)]">Günlük kota ve maliyet tavanı uygulanır. Model yanıtı analitiğe kopyalanmaz; otomatik yayın yoktur.</p></section><section><h2 className="text-sm font-extrabold">İnceleme kuyruğu</h2><div className="mt-3 space-y-4">{items.map((draft) => <DraftCard key={draft.id} draft={draft} onReviewed={reviewed} />)}{!items.length ? <p className="rounded-2xl border border-dashed border-[var(--site-line)] p-8 text-center text-sm text-[var(--site-muted)]">Henüz taslak yok.</p> : null}</div></section></div>;
}
