ALTER TYPE "OdOnboardingState" ADD VALUE IF NOT EXISTS 'ALTERNATE_SLOT_OFFERED' AFTER 'PLACEMENT_PENDING';
ALTER TYPE "OdOnboardingState" ADD VALUE IF NOT EXISTS 'ALTERNATE_SLOT_ACCEPTED' AFTER 'ALTERNATE_SLOT_OFFERED';
ALTER TYPE "OdOnboardingState" ADD VALUE IF NOT EXISTS 'WAITLISTED' AFTER 'ALTERNATE_SLOT_ACCEPTED';
ALTER TYPE "OdOnboardingState" ADD VALUE IF NOT EXISTS 'NO_SLOT_REFUND_PENDING' AFTER 'WAITLISTED';
