import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requireProductRole } from "@/lib/auth/guards";
import { getOdkExamReadiness } from "@/lib/odk/admin-exam-server";
import { PanelShell } from "@/components/panel/panel-shell";
import { AdminExamEditor } from "@/components/odk/admin-exam-editor";

export const dynamic = "force-dynamic";
function localInput(value: Date | null) { if (!value) return ""; return new Intl.DateTimeFormat("sv-SE", { timeZone: "Europe/Istanbul", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(value).replace(" ", "T"); }

export default async function OdkAdminExamDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireProductRole("ODK", "ADMIN"); const { id } = await params; const { exam, issues } = await getOdkExamReadiness(id); if (!exam?.currentVersion) notFound();
  const [outcomes, attempts] = await Promise.all([prisma.learningOutcome.findMany({ where: { isActive: true, unit: { subject: { version: { exam: exam.family, status: "ACTIVE" }, OR: [{ code: { contains: "MAT", mode: "insensitive" } }, { name: { contains: "Matematik", mode: "insensitive" } }] } } }, orderBy: [{ unit: { name: "asc" } }, { code: "asc" }], include: { unit: { select: { name: true } } }, take: 500 }), prisma.odkExamAttempt.findMany({ where: { examId: id, status: { not: "VOID" } }, select: { status: true, score: { select: { attemptId: true } } } })]);
  const questions = exam.currentVersion.sections.flatMap((section) => section.questions.map((question) => ({ id: question.id, questionNumber: question.questionNumber, correctOption: question.correctOption, difficulty: question.difficulty, bookletPage: question.bookletPage, outcomeIds: question.outcomes.map((outcome) => outcome.outcomeId), primaryOutcomeId: question.outcomes.find((outcome) => outcome.isPrimary)?.outcomeId || null })));
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} product="ODK"><Link href="/panel/odk/yonetim/sinavlar" className="panel-text-link"><ArrowLeft size={13} /> Denemelere dön</Link><header className="mt-5"><p className="text-xs font-extrabold uppercase text-[var(--brand-olive)]">{exam.family} · sürüm {exam.currentVersion.versionNumber}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{exam.title}</h1><p className="mt-2 text-sm text-[var(--site-body)]">İçerik kilitlendikten sonra cevap veya kazanım değişikliği için yeni sürüm gerekir.</p></header><div className="mt-7"><AdminExamEditor exam={{ id: exam.id, title: exam.title, family: exam.family, status: exam.status, startsAt: localInput(exam.startsAt), endsAt: localInput(exam.endsAt), lateEntryMinutes: exam.lateEntryMinutes, meetRequired: exam.meetRequired, meetUrl: exam.meetUrl || "", versionStatus: exam.currentVersion.status, durationMinutes: exam.currentVersion.durationMinutes, files: exam.currentVersion.files.map((file) => ({ id: file.id, type: file.type, fileName: file.fileName })), questions }} outcomes={outcomes.map((outcome) => ({ id: outcome.id, label: `${outcome.code} · ${outcome.unit.name} · ${outcome.title}` }))} issues={issues} resultStats={{ attemptCount: attempts.length, submittedCount: attempts.filter((attempt) => attempt.status === "SUBMITTED" || attempt.status === "AUTO_SUBMITTED").length, scoredCount: attempts.filter((attempt) => attempt.score).length, examEnded: Boolean(exam.endsAt && exam.endsAt <= new Date()) }} /></div></PanelShell>;
}
