import type { Metadata } from "next";
import Link from "next/link";
import { BarChart3, Compass, HeartHandshake, Target } from "lucide-react";
import { Navbar } from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";

export const metadata: Metadata = { title: "Hakkımızda", description: "Online Dershanem; canlı küçük grup dersini, belirli çalışma yönünü ve anlaşılır takibi tek düzende birleştirir.", alternates: { canonical: "/hakkimizda/" } };

export default function AboutPage() {
  return <><Navbar/><main className="bg-[#fffdf9] text-[var(--od-ink)]">
    <section className="od-container py-20 text-center sm:py-32"><p className="text-sm font-semibold text-[var(--od-orange)]">Online Dershanem</p><h1 className="mx-auto mt-5 max-w-5xl font-display text-[clamp(3.2rem,7vw,7rem)] leading-[.9] tracking-[-.04em]">Öğrencinin yalnız çalışmadığı bir hazırlık sistemi.</h1><p className="mx-auto mt-8 max-w-2xl text-lg leading-8 text-[var(--od-ink-soft)]">Canlı küçük grup dersini, belirli çalışma yönünü ve anlaşılır takibi tek bir düzende birleştiriyoruz.</p></section>
    <section className="od-container"><div className="od-card grid overflow-hidden lg:grid-cols-2"><div className="p-8 sm:p-14"><p className="text-sm font-semibold text-[var(--od-orange)]">Misyonumuz</p><h2 className="mt-5 font-display text-5xl leading-none sm:text-7xl">Hedefe giden yolu sadeleştirmek.</h2></div><div className="flex items-center bg-[#f3f1eb] p-8 sm:p-14"><p className="text-lg leading-8 text-[var(--od-ink-soft)]">Öğrencinin derste görünür kaldığı, ne çalışacağını bildiği ve gelişiminin aile için de anlaşılır olduğu sürdürülebilir bir çalışma düzeni kurmak.</p></div></div></section>
    <section className="od-container py-24"><div className="grid gap-5 md:grid-cols-3">{[[HeartHandshake,"Yakın destek","Öğrencinin soru sorabildiği ve çözümünü gösterebildiği küçük grup."],[BarChart3,"Görünür süreç","Ders sonrası plan, ödev ve kısa gelişim notuyla anlaşılır takip."],[Compass,"Belirli yön","Her dersin sonunda sonraki adımın ne olduğunu bilmek."]].map(([Icon,t,b])=>{const C=Icon as typeof BarChart3; return <article key={String(t)} className="od-card p-8"><div className="grid h-12 w-12 place-items-center rounded-full bg-[var(--od-orange-soft)] text-[var(--od-orange)]"><C size={22}/></div><h2 className="mt-8 font-display text-3xl">{String(t)}</h2><p className="mt-4 text-sm leading-6 text-[var(--od-ink-soft)]">{String(b)}</p></article>})}</div></section>
    <section className="border-y border-[var(--od-line)] bg-[#f7f6f2]"><div className="od-container grid gap-12 py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-semibold text-[var(--od-orange)]">Değerlerimiz</p><h2 className="mt-4 font-display text-5xl leading-none">İlerleme, küçük ama tutarlı adımlarla gelir.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[["Şeffaflık","Pakette ne olduğu ve operasyonun nasıl ilerlediği açıkça paylaşılır."],["Disiplin","Belirli ders ve çalışma ritmi, motivasyondan bağımsız bir zemin kurar."],["Sürdürülebilirlik","Kısa vadeli vaatler yerine uygulanabilir bir çalışma düzenine odaklanırız."],["Ölçülebilirlik","Ders, ödev ve geri bildirim üzerinden süreci görünür kılarız."]].map(([t,b])=><div key={t} className="rounded-2xl border border-[var(--od-line)] bg-white p-6"><h3 className="font-semibold">{t}</h3><p className="mt-2 text-sm leading-6 text-[var(--od-ink-soft)]">{b}</p></div>)}</div></div></section>
    <section className="od-container py-20 text-center sm:py-28"><Target className="mx-auto text-[var(--od-orange)]" size={32}/><h2 className="mx-auto mt-6 max-w-3xl font-display text-5xl leading-none sm:text-7xl">Hedefini birlikte planlayalım.</h2><Link href="/iletisim/" className="od-button od-button-primary mt-8">Ücretsiz görüşme</Link></section>
  </main><Footer/></>;
}
