import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, UsersRound } from "lucide-react";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth/guards";
import { PanelShell } from "@/components/panel/panel-shell";

export const dynamic = "force-dynamic";
const dateTime = new Intl.DateTimeFormat("tr-TR", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });

export default async function GroupDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireRole("ADMIN");
  const { id } = await params;
  const group = await prisma.group.findUnique({ where: { id }, include: { teacher: { select: { id: true, fullName: true, email: true } }, enrollments: { where: { endedAt: null }, include: { student: { include: { user: { select: { id: true, fullName: true, email: true } }, attendances: { take: 20, orderBy: { createdAt: "desc" } } } } } }, lessons: { orderBy: { startsAt: "desc" }, take: 24, include: { notes: true, attendances: true } }, assignments: { orderBy: { dueAt: "desc" }, take: 20, include: { progress: true } } } });
  if (!group) notFound();
  const completed = group.lessons.filter((lesson) => lesson.status === "COMPLETED").length;
  const planned = group.lessons.filter((lesson) => lesson.status === "PLANNED").length;
  return <PanelShell role={session.role} fullName={session.fullName} email={session.email} pageTitle="Grup detayı">
    <Link href="/panel/yonetim/egitim" className="panel-text-link"><ArrowLeft size={13} /> Eğitime dön</Link>
    <header className="mt-5 rounded-[14px] border border-[var(--site-line)] bg-white p-6 shadow-[var(--panel-card-shadow)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[9.5px] font-extrabold ${group.isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{group.isActive ? "Aktif grup" : "Kapalı grup"}</span><span className="text-[10.5px] text-[var(--site-muted)]">{group.level || "Seviye belirtilmedi"}</span></div><h1 className="mt-3 text-[26px] font-extrabold leading-[1.25] tracking-[-0.02em] text-[var(--site-ink)]">{group.name}</h1><p className="mt-2 text-sm text-[var(--site-body)]">{group.subject} · <Link href={`/panel/yonetim/kullanicilar/${group.teacher.id}`} className="font-bold text-[var(--brand-olive)]">{group.teacher.fullName || group.teacher.email}</Link></p></div><div className="flex gap-2"><span className="panel-quick-action"><UsersRound size={15} /> {group.enrollments.length}/{group.capacity} öğrenci</span><span className="panel-quick-action"><CalendarDays size={15} /> {group.lessons.length} ders</span></div></div></header>
    <section className="mt-5 grid gap-3 sm:grid-cols-3"><div className="panel-metric-card"><CheckCircle2 size={18} className="text-emerald-700" /><p className="mt-4 text-2xl font-bold text-[var(--site-ink)]">{completed}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Tamamlanan ders</p></div><div className="panel-metric-card"><Clock3 size={18} className="text-amber-700" /><p className="mt-4 text-2xl font-bold text-[var(--site-ink)]">{planned}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Planlı ders</p></div><div className="panel-metric-card"><UsersRound size={18} className="text-dc-brand-strong" /><p className="mt-4 text-2xl font-bold text-[var(--site-ink)]">{group.enrollments.length}</p><p className="mt-1 text-xs text-[var(--site-muted)]">Aktif öğrenci</p></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><section className="panel-surface p-5"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Öğrenciler</h2><div className="mt-4 space-y-2">{group.enrollments.map((enrollment) => { const records = enrollment.student.attendances; const attended = records.filter((item) => item.status === "PRESENT" || item.status === "LATE").length; return <Link key={enrollment.id} href={`/panel/yonetim/kullanicilar/${enrollment.student.user.id}`} className="flex items-center justify-between rounded-2xl border border-[var(--site-line)] p-3 hover:bg-[var(--site-bg-warm)]"><span><span className="block text-xs font-bold text-[var(--site-ink)]">{enrollment.student.user.fullName || enrollment.student.user.email}</span><span className="mt-1 block text-[10.5px] text-[var(--site-muted)]">Katılım {records.length ? `%${Math.round((attended / records.length) * 100)}` : "—"}</span></span><span className="text-xs font-bold text-[var(--brand-olive)]">Aç</span></Link>; })}{!group.enrollments.length ? <p className="text-xs text-[var(--site-muted)]">Aktif öğrenci yok.</p> : null}</div></section><section className="panel-surface"><div className="border-b border-[var(--site-line)] px-5 py-4"><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Ders geçmişi</h2></div><div className="divide-y divide-[var(--site-line)]">{group.lessons.map((lesson) => <article key={lesson.id} className="p-4 sm:px-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-[var(--site-ink)]">{lesson.title}</p><p className="mt-1 text-[10.5px] text-[var(--site-muted)]">{dateTime.format(lesson.startsAt)} · {lesson.attendances.length} yoklama · {lesson.notes.length} not</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold ${lesson.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : lesson.status === "CANCELLED" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-800"}`}>{lesson.status === "COMPLETED" ? "Tamamlandı" : lesson.status === "CANCELLED" ? "İptal" : "Planlı"}</span></div></article>)}{!group.lessons.length ? <p className="p-5 text-xs text-[var(--site-muted)]">Ders geçmişi yok.</p> : null}</div></section></div>
    <section className="panel-surface mt-5 p-5"><div className="flex items-end justify-between gap-3"><div><h2 className="text-sm font-extrabold text-[var(--site-ink)]">Ödev ilerlemesi</h2><p className="mt-1 text-xs text-[var(--site-muted)]">Öğrenci ve veli panelindeki durumun yönetim görünümü.</p></div><span className="text-xs font-bold text-[var(--site-muted)]">{group.assignments.length} ödev</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{group.assignments.map((assignment) => { const done = assignment.progress.filter((item) => item.status === "DONE").length; const percent = assignment.progress.length ? Math.round((done / assignment.progress.length) * 100) : 0; return <article key={assignment.id} className="rounded-2xl border border-[var(--site-line)] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xs font-bold text-[var(--site-ink)]">{assignment.title}</h3><p className="mt-1 text-[10.5px] text-[var(--site-muted)]">{dateTime.format(assignment.dueAt)} · {done}/{assignment.progress.length} tamamlandı</p></div><span className="text-sm font-extrabold text-[var(--brand-olive)]">%{percent}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-dc-line-soft" role="progressbar" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100} aria-label={`${assignment.title} tamamlanma oranı`}><div className="h-full rounded-full bg-dc-brand" style={{ width: `${percent}%` }} /></div></article>; })}{!group.assignments.length ? <p className="text-xs text-[var(--site-muted)]">Henüz ödev yok.</p> : null}</div></section>
  </PanelShell>;
}
